In [1]:
# Import Required Libraries
import polars as pl
import numpy as np

In [9]:
pl.Config.set_tbl_cols(-1)       # display.max.columns -> None (-1 means all)
pl.Config.set_tbl_rows(-1)       # display.max.rows -> None (-1 means all)
pl.Config.set_float_precision(2) # display.precision -> 2

polars.config.Config

In [10]:
# Load the Hip Replacement CCG data
# Load the Knee Replacement Provider data
df = pl.read_parquet(f'./data/interim/2.0-Hip-preprocessing.parquet')


# Make a copy of the original dataframe
df_original = df.clone()
print("Original dataframe copied to df_original.")

Original dataframe copied to df_original.

In [11]:
# Display basic information about the dataset
print("Shape of the dataset:", df.shape)
print("\nColumn names:")
print(df.columns)
print("\nData types:")
print(df.schema)
print("\nFirst 5 rows:")
df.head()

Shape of the dataset: (124844, 82)

Column names:
['Provider Code', 'Procedure', 'Revision Flag', 'Year', 'Age Band', 'Gender', 'Pre-Op Q Assisted', 'Pre-Op Q Assisted By', 'Pre-Op Q Symptom Period', 'Pre-Op Q Previous Surgery', 'Pre-Op Q Living Arrangements', 'Pre-Op Q Disability', 'Heart Disease', 'High Bp', 'Stroke', 'Circulation', 'Lung Disease', 'Diabetes', 'Kidney Disease', 'Nervous System', 'Liver Disease', 'Cancer', 'Depression', 'Arthritis', 'Pre-Op Q Mobility', 'Pre-Op Q Self-Care', 'Pre-Op Q Activity', 'Pre-Op Q Discomfort', 'Pre-Op Q Anxiety', 'Pre-Op Q EQ5D Index Profile', 'Pre-Op Q EQ5D Index', 'Post-Op Q Assisted', 'Post-Op Q Assisted By', 'Post-Op Q Living Arrangements', 'Post-Op Q Disability', 'Post-Op Q Mobility', 'Post-Op Q Self-Care', 'Post-Op Q Activity', 'Post-Op Q Discomfort', 'Post-Op Q Anxiety', 'Post-Op Q Satisfaction', 'Post-Op Q Sucess', 'Post-Op Q Allergy', 'Post-Op Q Bleeding', 'Post-Op Q Wound', 'Post-Op Q Urine', 'Post-Op Q Further Surgery', 'Post-Op Q Readmitted', 'Post-Op Q EQ5D Index Profile', 'Post-Op Q EQ5D Index', 'Hip Replacement EQ5D Index Post-Op Q Predicted', 'Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS', 'Hip Replacement EQ VAS Post-Op Q Predicted', 'Hip Replacement Pre-Op Q Pain', 'Hip Replacement Pre-Op Q Sudden Pain', 'Hip Replacement Pre-Op Q Night Pain', 'Hip Replacement Pre-Op Q Washing', 'Hip Replacement Pre-Op Q Transport', 'Hip Replacement Pre-Op Q Dressing', 'Hip Replacement Pre-Op Q Shopping', 'Hip Replacement Pre-Op Q Walking', 'Hip Replacement Pre-Op Q Limping', 'Hip Replacement Pre-Op Q Stairs', 'Hip Replacement Pre-Op Q Standing', 'Hip Replacement Pre-Op Q Work', 'Hip Replacement Pre-Op Q Score', 'Hip Replacement Post-Op Q Pain', 'Hip Replacement Post-Op Q Sudden Pain', 'Hip Replacement Post-Op Q Night Pain', 'Hip Replacement Post-Op Q Washing', 'Hip Replacement Post-Op Q Transport', 'Hip Replacement Post-Op Q Dressing', 'Hip Replacement Post-Op Q Shopping', 'Hip Replacement Post-Op Q Walking', 'Hip Replacement Post-Op Q Limping', 'Hip Replacement Post-Op Q Stairs', 'Hip Replacement Post-Op Q Standing', 'Hip Replacement Post-Op Q Work', 'Hip Replacement Post-Op Q Score', 'Hip Replacement OHS Post-Op Q Predicted', 'CSVYear']

Data types:
Schema([('Provider Code', Categorical), ('Procedure', Categorical), ('Revision Flag', UInt8), ('Year', Categorical), ('Age Band', Categorical), ('Gender', Float32), ('Pre-Op Q Assisted', UInt8), ('Pre-Op Q Assisted By', Int32), ('Pre-Op Q Symptom Period', UInt8), ('Pre-Op Q Previous Surgery', UInt8), ('Pre-Op Q Living Arrangements', UInt8), ('Pre-Op Q Disability', UInt8), ('Heart Disease', UInt8), ('High Bp', UInt8), ('Stroke', UInt8), ('Circulation', UInt8), ('Lung Disease', UInt8), ('Diabetes', UInt8), ('Kidney Disease', UInt8), ('Nervous System', UInt8), ('Liver Disease', UInt8), ('Cancer', UInt8), ('Depression', UInt8), ('Arthritis', UInt8), ('Pre-Op Q Mobility', UInt8), ('Pre-Op Q Self-Care', UInt8), ('Pre-Op Q Activity', UInt8), ('Pre-Op Q Discomfort', UInt8), ('Pre-Op Q Anxiety', UInt8), ('Pre-Op Q EQ5D Index Profile', UInt32), ('Pre-Op Q EQ5D Index', Float32), ('Post-Op Q Assisted', UInt8), ('Post-Op Q Assisted By', Int32), ('Post-Op Q Living Arrangements', UInt8), ('Post-Op Q Disability', UInt8), ('Post-Op Q Mobility', UInt8), ('Post-Op Q Self-Care', UInt8), ('Post-Op Q Activity', UInt8), ('Post-Op Q Discomfort', UInt8), ('Post-Op Q Anxiety', UInt8), ('Post-Op Q Satisfaction', UInt8), ('Post-Op Q Sucess', UInt8), ('Post-Op Q Allergy', UInt8), ('Post-Op Q Bleeding', UInt8), ('Post-Op Q Wound', UInt8), ('Post-Op Q Urine', UInt8), ('Post-Op Q Further Surgery', UInt8), ('Post-Op Q Readmitted', UInt8), ('Post-Op Q EQ5D Index Profile', UInt32), ('Post-Op Q EQ5D Index', Float32), ('Hip Replacement EQ5D Index Post-Op Q Predicted', Float32), ('Pre-Op Q EQ VAS', UInt16), ('Post-Op Q EQ VAS', UInt16), ('Hip Replacement EQ VAS Post-Op Q Predicted', Categorical), ('Hip Replacement Pre-Op Q Pain', UInt8), ('Hip Replacement Pre-Op Q Sudden Pain', UInt8), ('Hip Replacement Pre-Op Q Night Pain', UInt8), ('Hip Replacement Pre-Op Q Washing', UInt8), ('Hip Replacement Pre-Op Q Transport', UInt8), ('Hip Replacement Pre-Op Q Dressing', UInt8), ('Hip Replacement Pre-Op Q Shopping', UInt8), ('Hip Replacement Pre-Op Q Walking', UInt8), ('Hip Replacement Pre-Op Q Limping', UInt8), ('Hip Replacement Pre-Op Q Stairs', UInt8), ('Hip Replacement Pre-Op Q Standing', UInt8), ('Hip Replacement Pre-Op Q Work', UInt8), ('Hip Replacement Pre-Op Q Score', Float32), ('Hip Replacement Post-Op Q Pain', UInt8), ('Hip Replacement Post-Op Q Sudden Pain', UInt8), ('Hip Replacement Post-Op Q Night Pain', UInt8), ('Hip Replacement Post-Op Q Washing', UInt8), ('Hip Replacement Post-Op Q Transport', UInt8), ('Hip Replacement Post-Op Q Dressing', UInt8), ('Hip Replacement Post-Op Q Shopping', UInt8), ('Hip Replacement Post-Op Q Walking', UInt8), ('Hip Replacement Post-Op Q Limping', UInt8), ('Hip Replacement Post-Op Q Stairs', UInt8), ('Hip Replacement Post-Op Q Standing', UInt8), ('Hip Replacement Post-Op Q Work', UInt8), ('Hip Replacement Post-Op Q Score', Float32), ('Hip Replacement OHS Post-Op Q Predicted', Categorical), ('CSVYear', Categorical)])

First 5 rows:

shape: (5, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Pro ┆ Pro ┆ Rev ┆ Yea ┆ Age ┆ Gen ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Hea ┆ Hig ┆ Str ┆ Cir ┆ Lun ┆ Dia ┆ Kid ┆ Ner ┆ Liv ┆ Can ┆ Dep ┆ Art ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Hip ┆ Pre ┆ Pos ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ CSV │
│ vid ┆ ced ┆ isi ┆ r   ┆ Ban ┆ der ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ rt  ┆ h   ┆ oke ┆ cul ┆ g   ┆ bet ┆ ney ┆ vou ┆ er  ┆ cer ┆ res ┆ hri ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Rep ┆ -Op ┆ t-O ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Yea │
│ er  ┆ ure ┆ on  ┆ --- ┆ d   ┆ --- ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Dis ┆ Bp  ┆ --- ┆ ati ┆ Dis ┆ es  ┆ Dis ┆ s   ┆ Dis ┆ --- ┆ sio ┆ tis ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ lac ┆ Q   ┆ p Q ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ r   │
│ Cod ┆ --- ┆ Fla ┆ cat ┆ --- ┆ f32 ┆ Ass ┆ Ass ┆ Sym ┆ Pre ┆ Liv ┆ Dis ┆ eas ┆ --- ┆ u8  ┆ on  ┆ eas ┆ --- ┆ eas ┆ Sys ┆ eas ┆ u8  ┆ n   ┆ --- ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ EQ5 ┆ EQ5 ┆ Ass ┆ Ass ┆ Liv ┆ Dis ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ Sat ┆ Suc ┆ All ┆ Ble ┆ Wou ┆ Uri ┆ Fur ┆ Rea ┆ EQ5 ┆ EQ5 ┆ eme ┆ EQ  ┆ EQ  ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ --- │
│ e   ┆ cat ┆ g   ┆     ┆ cat ┆     ┆ ist ┆ ist ┆ pto ┆ vio ┆ ing ┆ abi ┆ e   ┆ u8  ┆     ┆ --- ┆ e   ┆ u8  ┆ e   ┆ tem ┆ e   ┆     ┆ --- ┆ u8  ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ D   ┆ D   ┆ ist ┆ ist ┆ ing ┆ abi ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ isf ┆ ess ┆ erg ┆ edi ┆ nd  ┆ ne  ┆ the ┆ dmi ┆ D   ┆ D   ┆ nt  ┆ VAS ┆ VAS ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ cat │
│ --- ┆     ┆ --- ┆     ┆     ┆     ┆ ed  ┆ ed  ┆ m   ┆ us  ┆ Arr ┆ lit ┆ --- ┆     ┆     ┆ u8  ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆     ┆ u8  ┆     ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ Ind ┆ Ind ┆ ed  ┆ ed  ┆ Arr ┆ lit ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ act ┆ --- ┆ y   ┆ ng  ┆ --- ┆ --- ┆ r   ┆ tte ┆ Ind ┆ Ind ┆ EQ5 ┆ --- ┆ --- ┆ EQ  ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ OHS ┆     │
│ cat ┆     ┆ u8  ┆     ┆     ┆     ┆ --- ┆ By  ┆ Per ┆ Sur ┆ ang ┆ y   ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ u8  ┆ u8  ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ex  ┆ ex  ┆ --- ┆ By  ┆ ang ┆ y   ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ion ┆ u8  ┆ --- ┆ --- ┆ u8  ┆ u8  ┆ Sur ┆ d   ┆ ex  ┆ ex  ┆ D   ┆ u16 ┆ u16 ┆ VAS ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Pos ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ iod ┆ ger ┆ eme ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ u8  ┆ --- ┆ u8  ┆ Pro ┆ --- ┆ u8  ┆ --- ┆ eme ┆ --- ┆ u8  ┆ u8  ┆ u8  ┆ --- ┆ u8  ┆ --- ┆     ┆ u8  ┆ u8  ┆     ┆     ┆ ger ┆ --- ┆ Pro ┆ --- ┆ Ind ┆     ┆     ┆ Pos ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ t-O ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ y   ┆ nts ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ fil ┆ f32 ┆     ┆ i32 ┆ nts ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ u8  ┆ fil ┆ f32 ┆ ex  ┆     ┆     ┆ t-O ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ p Q ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆     ┆ Pos ┆     ┆     ┆ p…  ┆ n   ┆ de… ┆ ht… ┆ hi… ┆ ns… ┆ ss… ┆ pp… ┆ ki… ┆ pi… ┆ ir… ┆ nd… ┆ k   ┆ re  ┆ n   ┆ d…  ┆ h…  ┆ h…  ┆ n…  ┆ s…  ┆ p…  ┆ k…  ┆ p…  ┆ i…  ┆ n…  ┆ k   ┆ r…  ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ …   ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ --- ┆     ┆     ┆ cat ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ f32 ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ f32 ┆ cat ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 2   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 999 ┆ nul ┆ 2   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 112 ┆ 0.8 ┆ nul ┆ nul ┆ 80  ┆ nul ┆ 0   ┆ 2   ┆ 1   ┆ 3   ┆ 1   ┆ 2   ┆ 3   ┆ 2   ┆ 1   ┆ 0   ┆ 2   ┆ 2   ┆ 19. ┆ 3   ┆ 4   ┆ 2   ┆ 4   ┆ 3   ┆ 2   ┆ 4   ┆ 4   ┆ 3   ┆ 2   ┆ 2   ┆ 3   ┆ 36. ┆ 3.7 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 99  ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ 8   ┆ l   ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 77. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 303 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .19 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     │
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 2   ┆ 1   ┆ 3   ┆ 2   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 1   ┆ 222 ┆ 0.0 ┆ 2   ┆ 0   ┆ 1   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 211 ┆ 0.8 ┆ 0.6 ┆ 30  ┆ 70  ┆ 6.5 ┆ 0   ┆ 1   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 13. ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 3   ┆ 3   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 46. ┆ 3.5 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 31  ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ 5   ┆ 7   ┆     ┆     ┆ 92. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 58. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 244 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 681 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .89 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .57 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     │
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 2   ┆ 2   ┆ 3   ┆ 3   ┆ 2   ┆ 223 ┆ -0. ┆ 2   ┆ 0   ┆ 1   ┆ 1   ┆ 2   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 212 ┆ 0.8 ┆ 0.7 ┆ 40  ┆ 60  ┆ 6.8 ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 7.0 ┆ 1   ┆ 4   ┆ 3   ┆ 3   ┆ 2   ┆ 3   ┆ 2   ┆ 4   ┆ 1   ┆ 2   ┆ 4   ┆ 2   ┆ 31. ┆ 3.2 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 32  ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ 1   ┆ 0   ┆     ┆     ┆ 10. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 93. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 332 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 405 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .78 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .43 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     │
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 2   ┆ 1   ┆ 4   ┆ 2   ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 1   ┆ 222 ┆ 0.0 ┆ 2   ┆ 0   ┆ 1   ┆ 2   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 1   ┆ 2   ┆ 1   ┆ 212 ┆ 0.6 ┆ 0.7 ┆ 50  ┆ 55  ┆ 6.8 ┆ 0   ┆ 4   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 3   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 21. ┆ 0   ┆ 0   ┆ 0   ┆ 3   ┆ 2   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 0   ┆ 15. ┆ 3.8 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 31  ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 22  ┆ 2   ┆ 1   ┆     ┆     ┆ 83. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 67. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 315 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 962 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .75 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .86 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     │
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 2   ┆ 1   ┆ 4   ┆ 2   ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 2   ┆ 222 ┆ -0. ┆ 2   ┆ 0   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 111 ┆ 1.0 ┆ 0.7 ┆ 20  ┆ 90  ┆ 7.2 ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 0   ┆ 2   ┆ 1   ┆ 0   ┆ 10. ┆ 4   ┆ 4   ┆ 3   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 47. ┆ 3.6 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 32  ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ 0   ┆ 4   ┆     ┆     ┆ 26. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 86. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 409 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 746 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .02 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     │

In [12]:
# Returns a 1-row DataFrame with counts for each column
print(df.null_count())

shape: (1, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Pro ┆ Pro ┆ Rev ┆ Yea ┆ Age ┆ Gen ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Hea ┆ Hig ┆ Str ┆ Cir ┆ Lun ┆ Dia ┆ Kid ┆ Ner ┆ Liv ┆ Can ┆ Dep ┆ Art ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Hip ┆ Pre ┆ Pos ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ CSV │
│ vid ┆ ced ┆ isi ┆ r   ┆ Ban ┆ der ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ rt  ┆ h   ┆ oke ┆ cul ┆ g   ┆ bet ┆ ney ┆ vou ┆ er  ┆ cer ┆ res ┆ hri ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Rep ┆ -Op ┆ t-O ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Yea │
│ er  ┆ ure ┆ on  ┆ --- ┆ d   ┆ --- ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Dis ┆ Bp  ┆ --- ┆ ati ┆ Dis ┆ es  ┆ Dis ┆ s   ┆ Dis ┆ --- ┆ sio ┆ tis ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ lac ┆ Q   ┆ p Q ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ r   │
│ Cod ┆ --- ┆ Fla ┆ u32 ┆ --- ┆ u32 ┆ Ass ┆ Ass ┆ Sym ┆ Pre ┆ Liv ┆ Dis ┆ eas ┆ --- ┆ u32 ┆ on  ┆ eas ┆ --- ┆ eas ┆ Sys ┆ eas ┆ u32 ┆ n   ┆ --- ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ EQ5 ┆ EQ5 ┆ Ass ┆ Ass ┆ Liv ┆ Dis ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ Sat ┆ Suc ┆ All ┆ Ble ┆ Wou ┆ Uri ┆ Fur ┆ Rea ┆ EQ5 ┆ EQ5 ┆ eme ┆ EQ  ┆ EQ  ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ --- │
│ e   ┆ u32 ┆ g   ┆     ┆ u32 ┆     ┆ ist ┆ ist ┆ pto ┆ vio ┆ ing ┆ abi ┆ e   ┆ u32 ┆     ┆ --- ┆ e   ┆ u32 ┆ e   ┆ tem ┆ e   ┆     ┆ --- ┆ u32 ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ D   ┆ D   ┆ ist ┆ ist ┆ ing ┆ abi ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ isf ┆ ess ┆ erg ┆ edi ┆ nd  ┆ ne  ┆ the ┆ dmi ┆ D   ┆ D   ┆ nt  ┆ VAS ┆ VAS ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ u32 │
│ --- ┆     ┆ --- ┆     ┆     ┆     ┆ ed  ┆ ed  ┆ m   ┆ us  ┆ Arr ┆ lit ┆ --- ┆     ┆     ┆ u32 ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆     ┆ u32 ┆     ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ Ind ┆ Ind ┆ ed  ┆ ed  ┆ Arr ┆ lit ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ act ┆ --- ┆ y   ┆ ng  ┆ --- ┆ --- ┆ r   ┆ tte ┆ Ind ┆ Ind ┆ EQ5 ┆ --- ┆ --- ┆ EQ  ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ OHS ┆     │
│ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆ --- ┆ By  ┆ Per ┆ Sur ┆ ang ┆ y   ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ex  ┆ ex  ┆ --- ┆ By  ┆ ang ┆ y   ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ion ┆ u32 ┆ --- ┆ --- ┆ u32 ┆ u32 ┆ Sur ┆ d   ┆ ex  ┆ ex  ┆ D   ┆ u32 ┆ u32 ┆ VAS ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Pos ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ iod ┆ ger ┆ eme ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ Pro ┆ --- ┆ u32 ┆ --- ┆ eme ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ --- ┆     ┆ u32 ┆ u32 ┆     ┆     ┆ ger ┆ --- ┆ Pro ┆ --- ┆ Ind ┆     ┆     ┆ Pos ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ t-O ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ y   ┆ nts ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ fil ┆ u32 ┆     ┆ u32 ┆ nts ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ u32 ┆ fil ┆ u32 ┆ ex  ┆     ┆     ┆ t-O ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ p Q ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆     ┆ Pos ┆     ┆     ┆ p…  ┆ n   ┆ de… ┆ ht… ┆ hi… ┆ ns… ┆ ss… ┆ pp… ┆ ki… ┆ pi… ┆ ir… ┆ nd… ┆ k   ┆ re  ┆ n   ┆ d…  ┆ h…  ┆ h…  ┆ n…  ┆ s…  ┆ p…  ┆ k…  ┆ p…  ┆ i…  ┆ n…  ┆ k   ┆ r…  ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ --- ┆     ┆ …   ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ --- ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 959 ┆ 959 ┆ 134 ┆ 0   ┆ 110 ┆ 915 ┆ 168 ┆ 734 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 414 ┆ 421 ┆ 429 ┆ 518 ┆ 484 ┆ 0   ┆ 702 ┆ 125 ┆ 0   ┆ 288 ┆ 456 ┆ 263 ┆ 239 ┆ 266 ┆ 344 ┆ 272 ┆ 201 ┆ 186 ┆ 101 ┆ 137 ┆ 119 ┆ 113 ┆ 185 ┆ 190 ┆ 0   ┆ 537 ┆ 130 ┆ 113 ┆ 609 ┆ 173 ┆ 183 ┆ 110 ┆ 107 ┆ 136 ┆ 111 ┆ 112 ┆ 114 ┆ 117 ┆ 111 ┆ 116 ┆ 113 ┆ 112 ┆ 568 ┆ 337 ┆ 792 ┆ 826 ┆ 320 ┆ 809 ┆ 814 ┆ 877 ┆ 110 ┆ 985 ┆ 943 ┆ 894 ┆ 962 ┆ 162 ┆ 403 ┆ 0   │
│     ┆     ┆     ┆     ┆ 1   ┆ 1   ┆ 6   ┆     ┆ 3   ┆     ┆ 0   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 9   ┆ 7   ┆ 8   ┆ 6   ┆     ┆ 0   ┆ 0   ┆     ┆ 9   ┆ 2   ┆ 7   ┆ 6   ┆ 9   ┆ 0   ┆ 2   ┆ 8   ┆ 0   ┆ 75  ┆ 18  ┆ 47  ┆ 81  ┆ 6   ┆ 2   ┆     ┆ 7   ┆ 06  ┆ 12  ┆ 9   ┆ 97  ┆     ┆ 6   ┆ 0   ┆     ┆ 9   ┆ 9   ┆ 2   ┆ 9   ┆ 1   ┆ 7   ┆ 7   ┆ 6   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [15]:
# Identify column types
numeric_dtypes = [pl.Int8, pl.Int16, pl.Int32, pl.Int64, pl.UInt8, pl.UInt16, pl.UInt32, pl.UInt64, pl.Float32, pl.Float64]
string_dtypes  = [pl.Utf8, pl.Categorical]  # parquet may store string columns as Categorical

numerical_cols = [c for c in df.columns if df[c].dtype in numeric_dtypes]
string_cols    = [c for c in df.columns if df[c].dtype in string_dtypes]

numerical_df = df.select(numerical_cols)
string_df    = df.select(string_cols)

print("List of numerical columns:")
print(numerical_cols)
print(f"\nList of string/categorical columns:")
print(string_cols)
print(f"\nNumerical dataframe shape: {numerical_df.shape}")
print(df.describe())

List of numerical columns:
['Revision Flag', 'Gender', 'Pre-Op Q Assisted', 'Pre-Op Q Assisted By', 'Pre-Op Q Symptom Period', 'Pre-Op Q Previous Surgery', 'Pre-Op Q Living Arrangements', 'Pre-Op Q Disability', 'Heart Disease', 'High Bp', 'Stroke', 'Circulation', 'Lung Disease', 'Diabetes', 'Kidney Disease', 'Nervous System', 'Liver Disease', 'Cancer', 'Depression', 'Arthritis', 'Pre-Op Q Mobility', 'Pre-Op Q Self-Care', 'Pre-Op Q Activity', 'Pre-Op Q Discomfort', 'Pre-Op Q Anxiety', 'Pre-Op Q EQ5D Index Profile', 'Pre-Op Q EQ5D Index', 'Post-Op Q Assisted', 'Post-Op Q Assisted By', 'Post-Op Q Living Arrangements', 'Post-Op Q Disability', 'Post-Op Q Mobility', 'Post-Op Q Self-Care', 'Post-Op Q Activity', 'Post-Op Q Discomfort', 'Post-Op Q Anxiety', 'Post-Op Q Satisfaction', 'Post-Op Q Sucess', 'Post-Op Q Allergy', 'Post-Op Q Bleeding', 'Post-Op Q Wound', 'Post-Op Q Urine', 'Post-Op Q Further Surgery', 'Post-Op Q Readmitted', 'Post-Op Q EQ5D Index Profile', 'Post-Op Q EQ5D Index', 'Hip Replacement EQ5D Index Post-Op Q Predicted', 'Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS', 'Hip Replacement Pre-Op Q Pain', 'Hip Replacement Pre-Op Q Sudden Pain', 'Hip Replacement Pre-Op Q Night Pain', 'Hip Replacement Pre-Op Q Washing', 'Hip Replacement Pre-Op Q Transport', 'Hip Replacement Pre-Op Q Dressing', 'Hip Replacement Pre-Op Q Shopping', 'Hip Replacement Pre-Op Q Walking', 'Hip Replacement Pre-Op Q Limping', 'Hip Replacement Pre-Op Q Stairs', 'Hip Replacement Pre-Op Q Standing', 'Hip Replacement Pre-Op Q Work', 'Hip Replacement Pre-Op Q Score', 'Hip Replacement Post-Op Q Pain', 'Hip Replacement Post-Op Q Sudden Pain', 'Hip Replacement Post-Op Q Night Pain', 'Hip Replacement Post-Op Q Washing', 'Hip Replacement Post-Op Q Transport', 'Hip Replacement Post-Op Q Dressing', 'Hip Replacement Post-Op Q Shopping', 'Hip Replacement Post-Op Q Walking', 'Hip Replacement Post-Op Q Limping', 'Hip Replacement Post-Op Q Stairs', 'Hip Replacement Post-Op Q Standing', 'Hip Replacement Post-Op Q Work', 'Hip Replacement Post-Op Q Score']

List of string/categorical columns:
['Provider Code', 'Procedure', 'Year', 'Age Band', 'Hip Replacement EQ VAS Post-Op Q Predicted', 'Hip Replacement OHS Post-Op Q Predicted', 'CSVYear']

Numerical dataframe shape: (124844, 75)
shape: (9, 83)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sta ┆ Pro ┆ Pro ┆ Rev ┆ Yea ┆ Age ┆ Gen ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Hea ┆ Hig ┆ Str ┆ Cir ┆ Lun ┆ Dia ┆ Kid ┆ Ner ┆ Liv ┆ Can ┆ Dep ┆ Art ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Hip ┆ Pre ┆ Pos ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ CSV │
│ tis ┆ vid ┆ ced ┆ isi ┆ r   ┆ Ban ┆ der ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ rt  ┆ h   ┆ oke ┆ cul ┆ g   ┆ bet ┆ ney ┆ vou ┆ er  ┆ cer ┆ res ┆ hri ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Rep ┆ -Op ┆ t-O ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Yea │
│ tic ┆ er  ┆ ure ┆ on  ┆ --- ┆ d   ┆ --- ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Dis ┆ Bp  ┆ --- ┆ ati ┆ Dis ┆ es  ┆ Dis ┆ s   ┆ Dis ┆ --- ┆ sio ┆ tis ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ lac ┆ Q   ┆ p Q ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ r   │
│ --- ┆ Cod ┆ --- ┆ Fla ┆ str ┆ --- ┆ f64 ┆ Ass ┆ Ass ┆ Sym ┆ Pre ┆ Liv ┆ Dis ┆ eas ┆ --- ┆ f64 ┆ on  ┆ eas ┆ --- ┆ eas ┆ Sys ┆ eas ┆ f64 ┆ n   ┆ --- ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ EQ5 ┆ EQ5 ┆ Ass ┆ Ass ┆ Liv ┆ Dis ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ Sat ┆ Suc ┆ All ┆ Ble ┆ Wou ┆ Uri ┆ Fur ┆ Rea ┆ EQ5 ┆ EQ5 ┆ eme ┆ EQ  ┆ EQ  ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ --- │
│ str ┆ e   ┆ str ┆ g   ┆     ┆ str ┆     ┆ ist ┆ ist ┆ pto ┆ vio ┆ ing ┆ abi ┆ e   ┆ f64 ┆     ┆ --- ┆ e   ┆ f64 ┆ e   ┆ tem ┆ e   ┆     ┆ --- ┆ f64 ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ D   ┆ D   ┆ ist ┆ ist ┆ ing ┆ abi ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ isf ┆ ess ┆ erg ┆ edi ┆ nd  ┆ ne  ┆ the ┆ dmi ┆ D   ┆ D   ┆ nt  ┆ VAS ┆ VAS ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ str │
│     ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆ ed  ┆ ed  ┆ m   ┆ us  ┆ Arr ┆ lit ┆ --- ┆     ┆     ┆ f64 ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆     ┆ f64 ┆     ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ Ind ┆ Ind ┆ ed  ┆ ed  ┆ Arr ┆ lit ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ act ┆ --- ┆ y   ┆ ng  ┆ --- ┆ --- ┆ r   ┆ tte ┆ Ind ┆ Ind ┆ EQ5 ┆ --- ┆ --- ┆ EQ  ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ OHS ┆     │
│     ┆ str ┆     ┆ f64 ┆     ┆     ┆     ┆ --- ┆ By  ┆ Per ┆ Sur ┆ ang ┆ y   ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ex  ┆ ex  ┆ --- ┆ By  ┆ ang ┆ y   ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ion ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ Sur ┆ d   ┆ ex  ┆ ex  ┆ D   ┆ f64 ┆ f64 ┆ VAS ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Pos ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ iod ┆ ger ┆ eme ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ Pro ┆ --- ┆ f64 ┆ --- ┆ eme ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆     ┆ ger ┆ --- ┆ Pro ┆ --- ┆ Ind ┆     ┆     ┆ Pos ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ t-O ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ y   ┆ nts ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ fil ┆ f64 ┆     ┆ f64 ┆ nts ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ f64 ┆ fil ┆ f64 ┆ ex  ┆     ┆     ┆ t-O ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ p Q ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆     ┆ Pos ┆     ┆     ┆ p…  ┆ n   ┆ de… ┆ ht… ┆ hi… ┆ ns… ┆ ss… ┆ pp… ┆ ki… ┆ pi… ┆ ir… ┆ nd… ┆ k   ┆ re  ┆ n   ┆ d…  ┆ h…  ┆ h…  ┆ n…  ┆ s…  ┆ p…  ┆ k…  ┆ p…  ┆ i…  ┆ n…  ┆ k   ┆ r…  ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆     ┆ …   ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆     ┆     ┆ str ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cou ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 115 ┆ 115 ┆ 123 ┆ 124 ┆ 123 ┆ 123 ┆ 123 ┆ 117 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 120 ┆ 120 ┆ 120 ┆ 119 ┆ 119 ┆ 124 ┆ 117 ┆ 123 ┆ 124 ┆ 121 ┆ 120 ┆ 122 ┆ 122 ┆ 122 ┆ 121 ┆ 122 ┆ 122 ┆ 122 ┆ 114 ┆ 111 ┆ 112 ┆ 113 ┆ 122 ┆ 122 ┆ 124 ┆ 119 ┆ 111 ┆ 113 ┆ 118 ┆ 107 ┆ 124 ┆ 123 ┆ 123 ┆ 124 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 119 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 120 ┆ 124 │
│ nt  ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 253 ┆ 253 ┆ 498 ┆ 844 ┆ 741 ┆ 929 ┆ 164 ┆ 503 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 844 ┆ 700 ┆ 625 ┆ 547 ┆ 656 ┆ 998 ┆ 844 ┆ 824 ┆ 594 ┆ 844 ┆ 955 ┆ 282 ┆ 207 ┆ 448 ┆ 175 ┆ 404 ┆ 122 ┆ 826 ┆ 984 ┆ 669 ┆ 126 ┆ 897 ┆ 463 ┆ 988 ┆ 942 ┆ 844 ┆ 467 ┆ 838 ┆ 532 ┆ 745 ┆ 447 ┆ 661 ┆ 738 ┆ 774 ┆ 708 ┆ 725 ┆ 715 ┆ 702 ┆ 665 ┆ 733 ┆ 677 ┆ 707 ┆ 718 ┆ 159 ┆ 507 ┆ 052 ┆ 018 ┆ 524 ┆ 035 ┆ 030 ┆ 967 ┆ 737 ┆ 859 ┆ 901 ┆ 950 ┆ 882 ┆ 217 ┆ 806 ┆ 844 │
│     ┆     ┆     ┆ .00 ┆     ┆     ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆     ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆     ┆     │
│ nul ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 959 ┆ 959 ┆ 134 ┆ 0.0 ┆ 110 ┆ 915 ┆ 168 ┆ 734 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 414 ┆ 421 ┆ 429 ┆ 518 ┆ 484 ┆ 0.0 ┆ 702 ┆ 125 ┆ 0.0 ┆ 288 ┆ 456 ┆ 263 ┆ 239 ┆ 266 ┆ 344 ┆ 272 ┆ 201 ┆ 186 ┆ 101 ┆ 137 ┆ 119 ┆ 113 ┆ 185 ┆ 190 ┆ 0.0 ┆ 537 ┆ 130 ┆ 113 ┆ 609 ┆ 173 ┆ 183 ┆ 110 ┆ 107 ┆ 136 ┆ 111 ┆ 112 ┆ 114 ┆ 117 ┆ 111 ┆ 116 ┆ 113 ┆ 112 ┆ 568 ┆ 337 ┆ 792 ┆ 826 ┆ 320 ┆ 809 ┆ 814 ┆ 877 ┆ 110 ┆ 985 ┆ 943 ┆ 894 ┆ 962 ┆ 162 ┆ 403 ┆ 0   │
│ l_c ┆     ┆     ┆ 0   ┆     ┆ 1   ┆ 1.0 ┆ 6.0 ┆ 0   ┆ 3.0 ┆ .00 ┆ 0.0 ┆ 1.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 4.0 ┆ 9.0 ┆ 7.0 ┆ 8.0 ┆ 6.0 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 9.0 ┆ 2.0 ┆ 7.0 ┆ 6.0 ┆ 9.0 ┆ 0.0 ┆ 2.0 ┆ 8.0 ┆ 0.0 ┆ 75. ┆ 18. ┆ 47. ┆ 81. ┆ 6.0 ┆ 2.0 ┆ 0   ┆ 7.0 ┆ 06. ┆ 12. ┆ 9.0 ┆ 97  ┆ .00 ┆ 6.0 ┆ 0.0 ┆ .00 ┆ 9.0 ┆ 9.0 ┆ 2.0 ┆ 9.0 ┆ 1.0 ┆ 7.0 ┆ 7.0 ┆ 6.0 ┆ 5.0 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ 7.0 ┆ .00 ┆ .00 ┆ .00 ┆ .00 ┆ 7.0 ┆ 8   ┆     │
│ oun ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 00  ┆ 00  ┆ 00  ┆ 00  ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 00  ┆ 00  ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ mea ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 1.6 ┆ 1.8 ┆ 1.0 ┆ 2.1 ┆ 1.9 ┆ 1.2 ┆ 1.4 ┆ 0.0 ┆ 0.3 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.7 ┆ 1.9 ┆ 1.5 ┆ 2.1 ┆ 2.4 ┆ 1.4 ┆ 237 ┆ 0.3 ┆ 1.9 ┆ 0.1 ┆ 1.2 ┆ 1.7 ┆ 1.3 ┆ 1.1 ┆ 1.4 ┆ 1.4 ┆ 1.2 ┆ 1.8 ┆ 1.2 ┆ 1.9 ┆ 1.9 ┆ 1.9 ┆ 1.8 ┆ 1.9 ┆ 1.9 ┆ 170 ┆ 0.8 ┆ 0.7 ┆ 63. ┆ 77. ┆ nul ┆ 0.5 ┆ 1.4 ┆ 0.9 ┆ 2.2 ┆ 1.8 ┆ 1.5 ┆ 1.8 ┆ 1.9 ┆ 0.6 ┆ 1.8 ┆ 1.6 ┆ 1.2 ┆ 18. ┆ 2.9 ┆ 3.5 ┆ 3.3 ┆ 3.5 ┆ 3.3 ┆ 2.9 ┆ 3.2 ┆ 3.4 ┆ 3.1 ┆ 3.2 ┆ 3.4 ┆ 3.3 ┆ 39. ┆ nul ┆ nul │
│ n   ┆ l   ┆ l   ┆ 5   ┆ l   ┆ l   ┆ 1   ┆ 4   ┆ 0   ┆ 3   ┆ 1   ┆ 7   ┆ 6   ┆ 9   ┆ 8   ┆ 1   ┆ 5   ┆ 8   ┆ 9   ┆ 2   ┆ 1   ┆ 1   ┆ 6   ┆ 8   ┆ 2   ┆ 3   ┆ 7   ┆ 3   ┆ 3   ┆ 7   ┆ 37. ┆ 4   ┆ 4   ┆ 1   ┆ 8   ┆ 2   ┆ 9   ┆ 9   ┆ 5   ┆ 6   ┆ 0   ┆ 7   ┆ 2   ┆ 0   ┆ 6   ┆ 2   ┆ 7   ┆ 8   ┆ 4   ┆ 21. ┆ 0   ┆ 8   ┆ 57  ┆ 24  ┆ l   ┆ 5   ┆ 1   ┆ 6   ┆ 5   ┆ 4   ┆ 1   ┆ 1   ┆ 1   ┆ 8   ┆ 4   ┆ 8   ┆ 9   ┆ 04  ┆ 5   ┆ 3   ┆ 1   ┆ 5   ┆ 4   ┆ 6   ┆ 6   ┆ 8   ┆ 7   ┆ 8   ┆ 6   ┆ 7   ┆ 74  ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 71  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ std ┆ nul ┆ nul ┆ 0.2 ┆ nul ┆ nul ┆ 0.4 ┆ 0.3 ┆ 0.0 ┆ 0.7 ┆ 0.2 ┆ 0.4 ┆ 0.5 ┆ 0.2 ┆ 0.4 ┆ 0.1 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.2 ┆ 0.2 ┆ 0.4 ┆ 0.2 ┆ 0.5 ┆ 0.4 ┆ 0.5 ┆ 0.5 ┆ 143 ┆ 0.3 ┆ 0.2 ┆ 0.3 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.5 ┆ 0.5 ┆ 0.4 ┆ 0.9 ┆ 0.6 ┆ 0.3 ┆ 0.1 ┆ 0.2 ┆ 0.3 ┆ 0.1 ┆ 0.2 ┆ 129 ┆ 0.2 ┆ 0.1 ┆ 22. ┆ 18. ┆ nul ┆ 0.6 ┆ 1.2 ┆ 1.0 ┆ 0.9 ┆ 0.7 ┆ 1.0 ┆ 1.2 ┆ 1.1 ┆ 0.9 ┆ 0.9 ┆ 0.8 ┆ 0.9 ┆ 8.2 ┆ 1.2 ┆ 0.9 ┆ 1.0 ┆ 0.7 ┆ 0.8 ┆ 1.1 ┆ 1.1 ┆ 0.9 ┆ 1.1 ┆ 0.9 ┆ 0.7 ┆ 0.9 ┆ 8.6 ┆ nul ┆ nul │
│     ┆ l   ┆ l   ┆ 2   ┆ l   ┆ l   ┆ 9   ┆ 6   ┆ 0   ┆ 1   ┆ 8   ┆ 7   ┆ 0   ┆ 8   ┆ 9   ┆ 2   ┆ 1   ┆ 8   ┆ 9   ┆ 4   ┆ 9   ┆ 8   ┆ 3   ┆ 8   ┆ 5   ┆ 7   ┆ 2   ┆ 9   ┆ 1   ┆ 9   ┆ 20. ┆ 2   ┆ 4   ┆ 1   ┆ 8   ┆ 5   ┆ 9   ┆ 0   ┆ 6   ┆ 6   ┆ 4   ┆ 7   ┆ 5   ┆ 1   ┆ 9   ┆ 7   ┆ 3   ┆ 5   ┆ 5   ┆ 66. ┆ 4   ┆ 1   ┆ 55  ┆ 00  ┆ l   ┆ 9   ┆ 3   ┆ 8   ┆ 9   ┆ 7   ┆ 2   ┆ 8   ┆ 7   ┆ 3   ┆ 6   ┆ 7   ┆ 2   ┆ 8   ┆ 7   ┆ 0   ┆ 5   ┆ 5   ┆ 2   ┆ 1   ┆ 7   ┆ 4   ┆ 2   ┆ 7   ┆ 8   ┆ 0   ┆ 4   ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 20  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ min ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 111 ┆ -0. ┆ 1.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 111 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ nul ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ nul ┆ nul │
│     ┆ l   ┆ l   ┆ 0   ┆ l   ┆ l   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 11. ┆ 59  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 11. ┆ 59  ┆ 9   ┆ 0   ┆ 0   ┆ l   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 25% ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 1.0 ┆ 2.0 ┆ 1.0 ┆ 2.0 ┆ 2.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 1.0 ┆ 2.0 ┆ 2.0 ┆ 1.0 ┆ 212 ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 111 ┆ 0.6 ┆ 0.7 ┆ 50. ┆ 70. ┆ nul ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 12. ┆ 2.0 ┆ 3.0 ┆ 3.0 ┆ 3.0 ┆ 3.0 ┆ 2.0 ┆ 3.0 ┆ 3.0 ┆ 3.0 ┆ 3.0 ┆ 3.0 ┆ 3.0 ┆ 36. ┆ nul ┆ nul │
│     ┆ l   ┆ l   ┆ 0   ┆ l   ┆ l   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 21. ┆ 5   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 11. ┆ 9   ┆ 1   ┆ 00  ┆ 00  ┆ l   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 00  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 00  ┆ l   ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 50% ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 2.0 ┆ 2.0 ┆ 1.0 ┆ 2.0 ┆ 2.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 1.0 ┆ 222 ┆ 0.5 ┆ 2.0 ┆ 0.0 ┆ 1.0 ┆ 2.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 2.0 ┆ 1.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 112 ┆ 0.8 ┆ 0.8 ┆ 70. ┆ 80. ┆ nul ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 2.0 ┆ 2.0 ┆ 1.0 ┆ 2.0 ┆ 2.0 ┆ 0.0 ┆ 2.0 ┆ 2.0 ┆ 1.0 ┆ 17. ┆ 3.0 ┆ 4.0 ┆ 4.0 ┆ 4.0 ┆ 4.0 ┆ 3.0 ┆ 4.0 ┆ 4.0 ┆ 4.0 ┆ 4.0 ┆ 4.0 ┆ 4.0 ┆ 43. ┆ nul ┆ nul │

In [16]:
# Print dataset overview
print("DATASET OVERVIEW:")
print(f"Total observations: {df.shape[0]}")
print(f"Total variables/columns: {df.shape[1]}")
print(f"\nNumerical variables/columns: {len(numerical_cols)}")
print(f"String variables/columns: {len(string_cols)}")

print(f"\nNumerical columns ({len(numerical_cols)}):")
print(numerical_cols)

print(f"\nString columns ({len(string_cols)}):")
print(string_cols)

print(f"\nNumerical dataframe shape: {numerical_df.shape}")
print(f"String dataframe shape: {string_df.shape}")

DATASET OVERVIEW:
Total observations: 124844
Total variables/columns: 82

Numerical variables/columns: 75
String variables/columns: 7

Numerical columns (75):
['Revision Flag', 'Gender', 'Pre-Op Q Assisted', 'Pre-Op Q Assisted By', 'Pre-Op Q Symptom Period', 'Pre-Op Q Previous Surgery', 'Pre-Op Q Living Arrangements', 'Pre-Op Q Disability', 'Heart Disease', 'High Bp', 'Stroke', 'Circulation', 'Lung Disease', 'Diabetes', 'Kidney Disease', 'Nervous System', 'Liver Disease', 'Cancer', 'Depression', 'Arthritis', 'Pre-Op Q Mobility', 'Pre-Op Q Self-Care', 'Pre-Op Q Activity', 'Pre-Op Q Discomfort', 'Pre-Op Q Anxiety', 'Pre-Op Q EQ5D Index Profile', 'Pre-Op Q EQ5D Index', 'Post-Op Q Assisted', 'Post-Op Q Assisted By', 'Post-Op Q Living Arrangements', 'Post-Op Q Disability', 'Post-Op Q Mobility', 'Post-Op Q Self-Care', 'Post-Op Q Activity', 'Post-Op Q Discomfort', 'Post-Op Q Anxiety', 'Post-Op Q Satisfaction', 'Post-Op Q Sucess', 'Post-Op Q Allergy', 'Post-Op Q Bleeding', 'Post-Op Q Wound', 'Post-Op Q Urine', 'Post-Op Q Further Surgery', 'Post-Op Q Readmitted', 'Post-Op Q EQ5D Index Profile', 'Post-Op Q EQ5D Index', 'Hip Replacement EQ5D Index Post-Op Q Predicted', 'Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS', 'Hip Replacement Pre-Op Q Pain', 'Hip Replacement Pre-Op Q Sudden Pain', 'Hip Replacement Pre-Op Q Night Pain', 'Hip Replacement Pre-Op Q Washing', 'Hip Replacement Pre-Op Q Transport', 'Hip Replacement Pre-Op Q Dressing', 'Hip Replacement Pre-Op Q Shopping', 'Hip Replacement Pre-Op Q Walking', 'Hip Replacement Pre-Op Q Limping', 'Hip Replacement Pre-Op Q Stairs', 'Hip Replacement Pre-Op Q Standing', 'Hip Replacement Pre-Op Q Work', 'Hip Replacement Pre-Op Q Score', 'Hip Replacement Post-Op Q Pain', 'Hip Replacement Post-Op Q Sudden Pain', 'Hip Replacement Post-Op Q Night Pain', 'Hip Replacement Post-Op Q Washing', 'Hip Replacement Post-Op Q Transport', 'Hip Replacement Post-Op Q Dressing', 'Hip Replacement Post-Op Q Shopping', 'Hip Replacement Post-Op Q Walking', 'Hip Replacement Post-Op Q Limping', 'Hip Replacement Post-Op Q Stairs', 'Hip Replacement Post-Op Q Standing', 'Hip Replacement Post-Op Q Work', 'Hip Replacement Post-Op Q Score']

String columns (7):
['Provider Code', 'Procedure', 'Year', 'Age Band', 'Hip Replacement EQ VAS Post-Op Q Predicted', 'Hip Replacement OHS Post-Op Q Predicted', 'CSVYear']

Numerical dataframe shape: (124844, 75)
String dataframe shape: (124844, 7)

In [17]:
# Check for missing values
null_counts = df.null_count()
print("Missing values per column:")
print(null_counts)

print("\nPercentage of missing values:")
print(null_counts / df.shape[0] * 100)

print("\nFirst 10 rows:")
df.head(10)

Missing values per column:
shape: (1, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Pro ┆ Pro ┆ Rev ┆ Yea ┆ Age ┆ Gen ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Hea ┆ Hig ┆ Str ┆ Cir ┆ Lun ┆ Dia ┆ Kid ┆ Ner ┆ Liv ┆ Can ┆ Dep ┆ Art ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Hip ┆ Pre ┆ Pos ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ CSV │
│ vid ┆ ced ┆ isi ┆ r   ┆ Ban ┆ der ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ rt  ┆ h   ┆ oke ┆ cul ┆ g   ┆ bet ┆ ney ┆ vou ┆ er  ┆ cer ┆ res ┆ hri ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Rep ┆ -Op ┆ t-O ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Yea │
│ er  ┆ ure ┆ on  ┆ --- ┆ d   ┆ --- ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Dis ┆ Bp  ┆ --- ┆ ati ┆ Dis ┆ es  ┆ Dis ┆ s   ┆ Dis ┆ --- ┆ sio ┆ tis ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ lac ┆ Q   ┆ p Q ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ r   │
│ Cod ┆ --- ┆ Fla ┆ u32 ┆ --- ┆ u32 ┆ Ass ┆ Ass ┆ Sym ┆ Pre ┆ Liv ┆ Dis ┆ eas ┆ --- ┆ u32 ┆ on  ┆ eas ┆ --- ┆ eas ┆ Sys ┆ eas ┆ u32 ┆ n   ┆ --- ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ EQ5 ┆ EQ5 ┆ Ass ┆ Ass ┆ Liv ┆ Dis ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ Sat ┆ Suc ┆ All ┆ Ble ┆ Wou ┆ Uri ┆ Fur ┆ Rea ┆ EQ5 ┆ EQ5 ┆ eme ┆ EQ  ┆ EQ  ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ --- │
│ e   ┆ u32 ┆ g   ┆     ┆ u32 ┆     ┆ ist ┆ ist ┆ pto ┆ vio ┆ ing ┆ abi ┆ e   ┆ u32 ┆     ┆ --- ┆ e   ┆ u32 ┆ e   ┆ tem ┆ e   ┆     ┆ --- ┆ u32 ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ D   ┆ D   ┆ ist ┆ ist ┆ ing ┆ abi ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ isf ┆ ess ┆ erg ┆ edi ┆ nd  ┆ ne  ┆ the ┆ dmi ┆ D   ┆ D   ┆ nt  ┆ VAS ┆ VAS ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ u32 │
│ --- ┆     ┆ --- ┆     ┆     ┆     ┆ ed  ┆ ed  ┆ m   ┆ us  ┆ Arr ┆ lit ┆ --- ┆     ┆     ┆ u32 ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆     ┆ u32 ┆     ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ Ind ┆ Ind ┆ ed  ┆ ed  ┆ Arr ┆ lit ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ act ┆ --- ┆ y   ┆ ng  ┆ --- ┆ --- ┆ r   ┆ tte ┆ Ind ┆ Ind ┆ EQ5 ┆ --- ┆ --- ┆ EQ  ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ OHS ┆     │
│ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆ --- ┆ By  ┆ Per ┆ Sur ┆ ang ┆ y   ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ex  ┆ ex  ┆ --- ┆ By  ┆ ang ┆ y   ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ion ┆ u32 ┆ --- ┆ --- ┆ u32 ┆ u32 ┆ Sur ┆ d   ┆ ex  ┆ ex  ┆ D   ┆ u32 ┆ u32 ┆ VAS ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Pos ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ iod ┆ ger ┆ eme ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ Pro ┆ --- ┆ u32 ┆ --- ┆ eme ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ --- ┆     ┆ u32 ┆ u32 ┆     ┆     ┆ ger ┆ --- ┆ Pro ┆ --- ┆ Ind ┆     ┆     ┆ Pos ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ t-O ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ y   ┆ nts ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ fil ┆ u32 ┆     ┆ u32 ┆ nts ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ u32 ┆ fil ┆ u32 ┆ ex  ┆     ┆     ┆ t-O ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ p Q ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆     ┆ Pos ┆     ┆     ┆ p…  ┆ n   ┆ de… ┆ ht… ┆ hi… ┆ ns… ┆ ss… ┆ pp… ┆ ki… ┆ pi… ┆ ir… ┆ nd… ┆ k   ┆ re  ┆ n   ┆ d…  ┆ h…  ┆ h…  ┆ n…  ┆ s…  ┆ p…  ┆ k…  ┆ p…  ┆ i…  ┆ n…  ┆ k   ┆ r…  ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ --- ┆     ┆ …   ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ --- ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 959 ┆ 959 ┆ 134 ┆ 0   ┆ 110 ┆ 915 ┆ 168 ┆ 734 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 414 ┆ 421 ┆ 429 ┆ 518 ┆ 484 ┆ 0   ┆ 702 ┆ 125 ┆ 0   ┆ 288 ┆ 456 ┆ 263 ┆ 239 ┆ 266 ┆ 344 ┆ 272 ┆ 201 ┆ 186 ┆ 101 ┆ 137 ┆ 119 ┆ 113 ┆ 185 ┆ 190 ┆ 0   ┆ 537 ┆ 130 ┆ 113 ┆ 609 ┆ 173 ┆ 183 ┆ 110 ┆ 107 ┆ 136 ┆ 111 ┆ 112 ┆ 114 ┆ 117 ┆ 111 ┆ 116 ┆ 113 ┆ 112 ┆ 568 ┆ 337 ┆ 792 ┆ 826 ┆ 320 ┆ 809 ┆ 814 ┆ 877 ┆ 110 ┆ 985 ┆ 943 ┆ 894 ┆ 962 ┆ 162 ┆ 403 ┆ 0   │
│     ┆     ┆     ┆     ┆ 1   ┆ 1   ┆ 6   ┆     ┆ 3   ┆     ┆ 0   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 9   ┆ 7   ┆ 8   ┆ 6   ┆     ┆ 0   ┆ 0   ┆     ┆ 9   ┆ 2   ┆ 7   ┆ 6   ┆ 9   ┆ 0   ┆ 2   ┆ 8   ┆ 0   ┆ 75  ┆ 18  ┆ 47  ┆ 81  ┆ 6   ┆ 2   ┆     ┆ 7   ┆ 06  ┆ 12  ┆ 9   ┆ 97  ┆     ┆ 6   ┆ 0   ┆     ┆ 9   ┆ 9   ┆ 2   ┆ 9   ┆ 1   ┆ 7   ┆ 7   ┆ 6   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

Percentage of missing values:
shape: (1, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Pro ┆ Pro ┆ Rev ┆ Yea ┆ Age ┆ Gen ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Hea ┆ Hig ┆ Str ┆ Cir ┆ Lun ┆ Dia ┆ Kid ┆ Ner ┆ Liv ┆ Can ┆ Dep ┆ Art ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Hip ┆ Pre ┆ Pos ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ CSV │
│ vid ┆ ced ┆ isi ┆ r   ┆ Ban ┆ der ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ rt  ┆ h   ┆ oke ┆ cul ┆ g   ┆ bet ┆ ney ┆ vou ┆ er  ┆ cer ┆ res ┆ hri ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Rep ┆ -Op ┆ t-O ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Yea │
│ er  ┆ ure ┆ on  ┆ --- ┆ d   ┆ --- ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Dis ┆ Bp  ┆ --- ┆ ati ┆ Dis ┆ es  ┆ Dis ┆ s   ┆ Dis ┆ --- ┆ sio ┆ tis ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ lac ┆ Q   ┆ p Q ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ r   │
│ Cod ┆ --- ┆ Fla ┆ f64 ┆ --- ┆ f64 ┆ Ass ┆ Ass ┆ Sym ┆ Pre ┆ Liv ┆ Dis ┆ eas ┆ --- ┆ f64 ┆ on  ┆ eas ┆ --- ┆ eas ┆ Sys ┆ eas ┆ f64 ┆ n   ┆ --- ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ EQ5 ┆ EQ5 ┆ Ass ┆ Ass ┆ Liv ┆ Dis ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ Sat ┆ Suc ┆ All ┆ Ble ┆ Wou ┆ Uri ┆ Fur ┆ Rea ┆ EQ5 ┆ EQ5 ┆ eme ┆ EQ  ┆ EQ  ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ --- │
│ e   ┆ f64 ┆ g   ┆     ┆ f64 ┆     ┆ ist ┆ ist ┆ pto ┆ vio ┆ ing ┆ abi ┆ e   ┆ f64 ┆     ┆ --- ┆ e   ┆ f64 ┆ e   ┆ tem ┆ e   ┆     ┆ --- ┆ f64 ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ D   ┆ D   ┆ ist ┆ ist ┆ ing ┆ abi ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ isf ┆ ess ┆ erg ┆ edi ┆ nd  ┆ ne  ┆ the ┆ dmi ┆ D   ┆ D   ┆ nt  ┆ VAS ┆ VAS ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ f64 │
│ --- ┆     ┆ --- ┆     ┆     ┆     ┆ ed  ┆ ed  ┆ m   ┆ us  ┆ Arr ┆ lit ┆ --- ┆     ┆     ┆ f64 ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆     ┆ f64 ┆     ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ Ind ┆ Ind ┆ ed  ┆ ed  ┆ Arr ┆ lit ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ act ┆ --- ┆ y   ┆ ng  ┆ --- ┆ --- ┆ r   ┆ tte ┆ Ind ┆ Ind ┆ EQ5 ┆ --- ┆ --- ┆ EQ  ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ OHS ┆     │
│ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ --- ┆ By  ┆ Per ┆ Sur ┆ ang ┆ y   ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ex  ┆ ex  ┆ --- ┆ By  ┆ ang ┆ y   ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ion ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ Sur ┆ d   ┆ ex  ┆ ex  ┆ D   ┆ f64 ┆ f64 ┆ VAS ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Pos ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ iod ┆ ger ┆ eme ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ Pro ┆ --- ┆ f64 ┆ --- ┆ eme ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆     ┆ ger ┆ --- ┆ Pro ┆ --- ┆ Ind ┆     ┆     ┆ Pos ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ t-O ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ y   ┆ nts ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ fil ┆ f64 ┆     ┆ f64 ┆ nts ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ f64 ┆ fil ┆ f64 ┆ ex  ┆     ┆     ┆ t-O ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ p Q ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆     ┆ Pos ┆     ┆     ┆ p…  ┆ n   ┆ de… ┆ ht… ┆ hi… ┆ ns… ┆ ss… ┆ pp… ┆ ki… ┆ pi… ┆ ir… ┆ nd… ┆ k   ┆ re  ┆ n   ┆ d…  ┆ h…  ┆ h…  ┆ n…  ┆ s…  ┆ p…  ┆ k…  ┆ p…  ┆ i…  ┆ n…  ┆ k   ┆ r…  ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆     ┆ …   ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 7.6 ┆ 7.6 ┆ 1.0 ┆ 0.0 ┆ 0.8 ┆ 0.7 ┆ 1.3 ┆ 5.8 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 3.3 ┆ 3.3 ┆ 3.4 ┆ 4.1 ┆ 3.8 ┆ 0.0 ┆ 5.6 ┆ 1.0 ┆ 0.0 ┆ 2.3 ┆ 3.6 ┆ 2.1 ┆ 1.9 ┆ 2.1 ┆ 2.7 ┆ 2.1 ┆ 1.6 ┆ 1.4 ┆ 8.1 ┆ 10. ┆ 9.5 ┆ 9.1 ┆ 1.4 ┆ 1.5 ┆ 0.0 ┆ 4.3 ┆ 10. ┆ 9.0 ┆ 4.8 ┆ 13. ┆ 0.1 ┆ 0.8 ┆ 0.8 ┆ 0.1 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.8 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 4.5 ┆ 0.2 ┆ 0.6 ┆ 0.6 ┆ 0.2 ┆ 0.6 ┆ 0.6 ┆ 0.7 ┆ 0.8 ┆ 0.7 ┆ 0.7 ┆ 0.7 ┆ 0.7 ┆ 1.3 ┆ 3.2 ┆ 0.0 │
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 8   ┆ 8   ┆ 8   ┆ 0   ┆ 8   ┆ 3   ┆ 5   ┆ 8   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 8   ┆ 4   ┆ 6   ┆ 8   ┆ 0   ┆ 2   ┆ 0   ┆ 0   ┆ 1   ┆ 5   ┆ 1   ┆ 2   ┆ 4   ┆ 6   ┆ 8   ┆ 2   ┆ 9   ┆ 5   ┆ 99  ┆ 7   ┆ 2   ┆ 9   ┆ 2   ┆ 0   ┆ 1   ┆ 42  ┆ 6   ┆ 9   ┆ 93  ┆ 5   ┆ 9   ┆ 6   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 4   ┆ 9   ┆ 3   ┆ 1   ┆ 0   ┆ 5   ┆ 7   ┆ 3   ┆ 6   ┆ 6   ┆ 5   ┆ 5   ┆ 0   ┆ 9   ┆ 9   ┆ 6   ┆ 2   ┆ 7   ┆ 0   ┆ 3   ┆ 0   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

First 10 rows:

shape: (10, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Pro ┆ Pro ┆ Rev ┆ Yea ┆ Age ┆ Gen ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Hea ┆ Hig ┆ Str ┆ Cir ┆ Lun ┆ Dia ┆ Kid ┆ Ner ┆ Liv ┆ Can ┆ Dep ┆ Art ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Hip ┆ Pre ┆ Pos ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ CSV │
│ vid ┆ ced ┆ isi ┆ r   ┆ Ban ┆ der ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ rt  ┆ h   ┆ oke ┆ cul ┆ g   ┆ bet ┆ ney ┆ vou ┆ er  ┆ cer ┆ res ┆ hri ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Rep ┆ -Op ┆ t-O ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Yea │
│ er  ┆ ure ┆ on  ┆ --- ┆ d   ┆ --- ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Dis ┆ Bp  ┆ --- ┆ ati ┆ Dis ┆ es  ┆ Dis ┆ s   ┆ Dis ┆ --- ┆ sio ┆ tis ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ lac ┆ Q   ┆ p Q ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ r   │
│ Cod ┆ --- ┆ Fla ┆ cat ┆ --- ┆ f32 ┆ Ass ┆ Ass ┆ Sym ┆ Pre ┆ Liv ┆ Dis ┆ eas ┆ --- ┆ u8  ┆ on  ┆ eas ┆ --- ┆ eas ┆ Sys ┆ eas ┆ u8  ┆ n   ┆ --- ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ EQ5 ┆ EQ5 ┆ Ass ┆ Ass ┆ Liv ┆ Dis ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ Sat ┆ Suc ┆ All ┆ Ble ┆ Wou ┆ Uri ┆ Fur ┆ Rea ┆ EQ5 ┆ EQ5 ┆ eme ┆ EQ  ┆ EQ  ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ --- │
│ e   ┆ cat ┆ g   ┆     ┆ cat ┆     ┆ ist ┆ ist ┆ pto ┆ vio ┆ ing ┆ abi ┆ e   ┆ u8  ┆     ┆ --- ┆ e   ┆ u8  ┆ e   ┆ tem ┆ e   ┆     ┆ --- ┆ u8  ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ D   ┆ D   ┆ ist ┆ ist ┆ ing ┆ abi ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ isf ┆ ess ┆ erg ┆ edi ┆ nd  ┆ ne  ┆ the ┆ dmi ┆ D   ┆ D   ┆ nt  ┆ VAS ┆ VAS ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ cat │
│ --- ┆     ┆ --- ┆     ┆     ┆     ┆ ed  ┆ ed  ┆ m   ┆ us  ┆ Arr ┆ lit ┆ --- ┆     ┆     ┆ u8  ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆     ┆ u8  ┆     ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ Ind ┆ Ind ┆ ed  ┆ ed  ┆ Arr ┆ lit ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ act ┆ --- ┆ y   ┆ ng  ┆ --- ┆ --- ┆ r   ┆ tte ┆ Ind ┆ Ind ┆ EQ5 ┆ --- ┆ --- ┆ EQ  ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ OHS ┆     │
│ cat ┆     ┆ u8  ┆     ┆     ┆     ┆ --- ┆ By  ┆ Per ┆ Sur ┆ ang ┆ y   ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ u8  ┆ u8  ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ex  ┆ ex  ┆ --- ┆ By  ┆ ang ┆ y   ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ion ┆ u8  ┆ --- ┆ --- ┆ u8  ┆ u8  ┆ Sur ┆ d   ┆ ex  ┆ ex  ┆ D   ┆ u16 ┆ u16 ┆ VAS ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Pos ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ iod ┆ ger ┆ eme ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ u8  ┆ --- ┆ u8  ┆ Pro ┆ --- ┆ u8  ┆ --- ┆ eme ┆ --- ┆ u8  ┆ u8  ┆ u8  ┆ --- ┆ u8  ┆ --- ┆     ┆ u8  ┆ u8  ┆     ┆     ┆ ger ┆ --- ┆ Pro ┆ --- ┆ Ind ┆     ┆     ┆ Pos ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ t-O ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ y   ┆ nts ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ fil ┆ f32 ┆     ┆ i32 ┆ nts ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ u8  ┆ fil ┆ f32 ┆ ex  ┆     ┆     ┆ t-O ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ p Q ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆     ┆ Pos ┆     ┆     ┆ p…  ┆ n   ┆ de… ┆ ht… ┆ hi… ┆ ns… ┆ ss… ┆ pp… ┆ ki… ┆ pi… ┆ ir… ┆ nd… ┆ k   ┆ re  ┆ n   ┆ d…  ┆ h…  ┆ h…  ┆ n…  ┆ s…  ┆ p…  ┆ k…  ┆ p…  ┆ i…  ┆ n…  ┆ k   ┆ r…  ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ …   ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ --- ┆     ┆     ┆ cat ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ f32 ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ f32 ┆ cat ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 2   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 999 ┆ nul ┆ 2   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 112 ┆ 0.8 ┆ nul ┆ nul ┆ 80  ┆ nul ┆ 0   ┆ 2   ┆ 1   ┆ 3   ┆ 1   ┆ 2   ┆ 3   ┆ 2   ┆ 1   ┆ 0   ┆ 2   ┆ 2   ┆ 19. ┆ 3   ┆ 4   ┆ 2   ┆ 4   ┆ 3   ┆ 2   ┆ 4   ┆ 4   ┆ 3   ┆ 2   ┆ 2   ┆ 3   ┆ 36. ┆ 3.7 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 99  ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ 8   ┆ l   ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 77. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 303 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .19 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     │
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 2   ┆ 1   ┆ 3   ┆ 2   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 1   ┆ 222 ┆ 0.0 ┆ 2   ┆ 0   ┆ 1   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 211 ┆ 0.8 ┆ 0.6 ┆ 30  ┆ 70  ┆ 6.5 ┆ 0   ┆ 1   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 13. ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 3   ┆ 3   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 46. ┆ 3.5 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 31  ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ 5   ┆ 7   ┆     ┆     ┆ 92. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 58. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 244 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 681 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .89 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .57 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     │
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 2   ┆ 2   ┆ 3   ┆ 3   ┆ 2   ┆ 223 ┆ -0. ┆ 2   ┆ 0   ┆ 1   ┆ 1   ┆ 2   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 212 ┆ 0.8 ┆ 0.7 ┆ 40  ┆ 60  ┆ 6.8 ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 7.0 ┆ 1   ┆ 4   ┆ 3   ┆ 3   ┆ 2   ┆ 3   ┆ 2   ┆ 4   ┆ 1   ┆ 2   ┆ 4   ┆ 2   ┆ 31. ┆ 3.2 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 32  ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ 1   ┆ 0   ┆     ┆     ┆ 10. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 93. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 332 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 405 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .78 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .43 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     │
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 2   ┆ 1   ┆ 4   ┆ 2   ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 1   ┆ 222 ┆ 0.0 ┆ 2   ┆ 0   ┆ 1   ┆ 2   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 1   ┆ 2   ┆ 1   ┆ 212 ┆ 0.6 ┆ 0.7 ┆ 50  ┆ 55  ┆ 6.8 ┆ 0   ┆ 4   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 3   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 21. ┆ 0   ┆ 0   ┆ 0   ┆ 3   ┆ 2   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 0   ┆ 15. ┆ 3.8 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 31  ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 22  ┆ 2   ┆ 1   ┆     ┆     ┆ 83. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 67. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 315 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 962 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .75 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .86 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     │
│ ADP ┆ Hip ┆ 0   ┆ 201 ┆ nul ┆ nul ┆ 2   ┆ 1   ┆ 4   ┆ 2   ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 2   ┆ 222 ┆ -0. ┆ 2   ┆ 0   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 111 ┆ 1.0 ┆ 0.7 ┆ 20  ┆ 90  ┆ 7.2 ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 0   ┆ 2   ┆ 1   ┆ 0   ┆ 10. ┆ 4   ┆ 4   ┆ 3   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 4   ┆ 47. ┆ 3.6 ┆ 201 │
│ 02  ┆ Rep ┆     ┆ 6/1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 32  ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ 0   ┆ 4   ┆     ┆     ┆ 26. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 86. ┆ 6/1 │
│     ┆ lac ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 409 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 746 ┆ 7   │
│     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .02 ┆     │
│     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     │

In [18]:
# Analyze missing values by Age Band
missing_by_age = (
    df.group_by('Age Band')
    .agg([pl.col(c).is_null().sum().alias(c) for c in df.columns if c != 'Age Band'])
    .sort('Age Band')
)
print("Missing values by Age Band:")
print(missing_by_age)

Missing values by Age Band:
shape: (9, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Age ┆ Pro ┆ Pro ┆ Rev ┆ Yea ┆ Gen ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Hea ┆ Hig ┆ Str ┆ Cir ┆ Lun ┆ Dia ┆ Kid ┆ Ner ┆ Liv ┆ Can ┆ Dep ┆ Art ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Hip ┆ Pre ┆ Pos ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ Hip ┆ CSV │
│ Ban ┆ vid ┆ ced ┆ isi ┆ r   ┆ der ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ rt  ┆ h   ┆ oke ┆ cul ┆ g   ┆ bet ┆ ney ┆ vou ┆ er  ┆ cer ┆ res ┆ hri ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Rep ┆ -Op ┆ t-O ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Rep ┆ Yea │
│ d   ┆ er  ┆ ure ┆ on  ┆ --- ┆ --- ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Dis ┆ Bp  ┆ --- ┆ ati ┆ Dis ┆ es  ┆ Dis ┆ s   ┆ Dis ┆ --- ┆ sio ┆ tis ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ lac ┆ Q   ┆ p Q ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ lac ┆ r   │
│ --- ┆ Cod ┆ --- ┆ Fla ┆ u32 ┆ u32 ┆ Ass ┆ Ass ┆ Sym ┆ Pre ┆ Liv ┆ Dis ┆ eas ┆ --- ┆ u32 ┆ on  ┆ eas ┆ --- ┆ eas ┆ Sys ┆ eas ┆ u32 ┆ n   ┆ --- ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ EQ5 ┆ EQ5 ┆ Ass ┆ Ass ┆ Liv ┆ Dis ┆ Mob ┆ Sel ┆ Act ┆ Dis ┆ Anx ┆ Sat ┆ Suc ┆ All ┆ Ble ┆ Wou ┆ Uri ┆ Fur ┆ Rea ┆ EQ5 ┆ EQ5 ┆ eme ┆ EQ  ┆ EQ  ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ eme ┆ --- │
│ cat ┆ e   ┆ u32 ┆ g   ┆     ┆     ┆ ist ┆ ist ┆ pto ┆ vio ┆ ing ┆ abi ┆ e   ┆ u32 ┆     ┆ --- ┆ e   ┆ u32 ┆ e   ┆ tem ┆ e   ┆     ┆ --- ┆ u32 ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ D   ┆ D   ┆ ist ┆ ist ┆ ing ┆ abi ┆ ili ┆ f-C ┆ ivi ┆ com ┆ iet ┆ isf ┆ ess ┆ erg ┆ edi ┆ nd  ┆ ne  ┆ the ┆ dmi ┆ D   ┆ D   ┆ nt  ┆ VAS ┆ VAS ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ nt  ┆ u32 │
│     ┆ --- ┆     ┆ --- ┆     ┆     ┆ ed  ┆ ed  ┆ m   ┆ us  ┆ Arr ┆ lit ┆ --- ┆     ┆     ┆ u32 ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆     ┆ u32 ┆     ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ Ind ┆ Ind ┆ ed  ┆ ed  ┆ Arr ┆ lit ┆ ty  ┆ are ┆ ty  ┆ for ┆ y   ┆ act ┆ --- ┆ y   ┆ ng  ┆ --- ┆ --- ┆ r   ┆ tte ┆ Ind ┆ Ind ┆ EQ5 ┆ --- ┆ --- ┆ EQ  ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pre ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ Pos ┆ OHS ┆     │
│     ┆ u32 ┆     ┆ u32 ┆     ┆     ┆ --- ┆ By  ┆ Per ┆ Sur ┆ ang ┆ y   ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ex  ┆ ex  ┆ --- ┆ By  ┆ ang ┆ y   ┆ --- ┆ --- ┆ --- ┆ t   ┆ --- ┆ ion ┆ u32 ┆ --- ┆ --- ┆ u32 ┆ u32 ┆ Sur ┆ d   ┆ ex  ┆ ex  ┆ D   ┆ u32 ┆ u32 ┆ VAS ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ -Op ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ t-O ┆ Pos ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ iod ┆ ger ┆ eme ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ Pro ┆ --- ┆ u32 ┆ --- ┆ eme ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ --- ┆     ┆ u32 ┆ u32 ┆     ┆     ┆ ger ┆ --- ┆ Pro ┆ --- ┆ Ind ┆     ┆     ┆ Pos ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ Q   ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ p Q ┆ t-O ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ y   ┆ nts ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ fil ┆ u32 ┆     ┆ u32 ┆ nts ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ u32 ┆ fil ┆ u32 ┆ ex  ┆     ┆     ┆ t-O ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ Pai ┆ Sud ┆ Nig ┆ Was ┆ Tra ┆ Dre ┆ Sho ┆ Wal ┆ Lim ┆ Sta ┆ Sta ┆ Wor ┆ Sco ┆ p Q ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆     ┆ Pos ┆     ┆     ┆ p…  ┆ n   ┆ de… ┆ ht… ┆ hi… ┆ ns… ┆ ss… ┆ pp… ┆ ki… ┆ pi… ┆ ir… ┆ nd… ┆ k   ┆ re  ┆ n   ┆ d…  ┆ h…  ┆ h…  ┆ n…  ┆ s…  ┆ p…  ┆ k…  ┆ p…  ┆ i…  ┆ n…  ┆ k   ┆ r…  ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ --- ┆     ┆ …   ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ --- ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ nul ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 959 ┆ 89  ┆ 0   ┆ 47  ┆ 51  ┆ 88  ┆ 486 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 275 ┆ 274 ┆ 285 ┆ 365 ┆ 307 ┆ 0   ┆ 484 ┆ 101 ┆ 0   ┆ 217 ┆ 337 ┆ 168 ┆ 163 ┆ 180 ┆ 210 ┆ 181 ┆ 165 ┆ 157 ┆ 121 ┆ 143 ┆ 129 ┆ 125 ┆ 152 ┆ 157 ┆ 0   ┆ 352 ┆ 843 ┆ 751 ┆ 412 ┆ 113 ┆ 13  ┆ 82  ┆ 80  ┆ 16  ┆ 86  ┆ 85  ┆ 89  ┆ 88  ┆ 82  ┆ 84  ┆ 89  ┆ 85  ┆ 422 ┆ 26  ┆ 60  ┆ 65  ┆ 33  ┆ 70  ┆ 69  ┆ 71  ┆ 82  ┆ 70  ┆ 77  ┆ 70  ┆ 85  ┆ 139 ┆ 264 ┆ 0   │
│ l   ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ 6   ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 20  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 2   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 4   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 0   ┆ 1   ┆ 1   ┆ 3   ┆ 0   │
│ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 29  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 30  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 11  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 2   ┆ 1   ┆ 1   ┆ 1   ┆ 0   ┆ 3   ┆ 0   ┆ 0   ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 2   ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 4   ┆ 9   ┆ 6   ┆ 6   ┆ 0   ┆ 2   ┆ 0   ┆ 3   ┆ 9   ┆ 5   ┆ 3   ┆ 12  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 7   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 4   ┆ 0   │
│ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 39  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 40  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 8   ┆ 0   ┆ 13  ┆ 15  ┆ 16  ┆ 142 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 21  ┆ 18  ┆ 28  ┆ 50  ┆ 27  ┆ 0   ┆ 79  ┆ 11  ┆ 0   ┆ 19  ┆ 73  ┆ 23  ┆ 27  ┆ 27  ┆ 33  ┆ 21  ┆ 15  ┆ 17  ┆ 79  ┆ 111 ┆ 91  ┆ 97  ┆ 19  ┆ 21  ┆ 0   ┆ 56  ┆ 189 ┆ 96  ┆ 63  ┆ 207 ┆ 8   ┆ 10  ┆ 7   ┆ 5   ┆ 11  ┆ 11  ┆ 10  ┆ 10  ┆ 10  ┆ 10  ┆ 12  ┆ 9   ┆ 81  ┆ 4   ┆ 5   ┆ 6   ┆ 6   ┆ 9   ┆ 9   ┆ 9   ┆ 11  ┆ 9   ┆ 9   ┆ 7   ┆ 8   ┆ 18  ┆ 96  ┆ 0   │
│ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 49  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 50  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 98  ┆ 0   ┆ 97  ┆ 85  ┆ 92  ┆ 889 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 271 ┆ 267 ┆ 284 ┆ 394 ┆ 312 ┆ 0   ┆ 551 ┆ 63  ┆ 0   ┆ 158 ┆ 401 ┆ 179 ┆ 155 ┆ 174 ┆ 259 ┆ 192 ┆ 141 ┆ 120 ┆ 848 ┆ 117 ┆ 992 ┆ 994 ┆ 122 ┆ 129 ┆ 0   ┆ 389 ┆ 109 ┆ 904 ┆ 457 ┆ 145 ┆ 13  ┆ 71  ┆ 68  ┆ 7   ┆ 75  ┆ 74  ┆ 79  ┆ 88  ┆ 69  ┆ 85  ┆ 72  ┆ 70  ┆ 560 ┆ 15  ┆ 48  ┆ 46  ┆ 15  ┆ 50  ┆ 48  ┆ 56  ┆ 67  ┆ 54  ┆ 64  ┆ 48  ┆ 55  ┆ 114 ┆ 380 ┆ 0   │
│ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 59  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 60  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 320 ┆ 0   ┆ 282 ┆ 227 ┆ 365 ┆ 212 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 100 ┆ 100 ┆ 104 ┆ 132 ┆ 116 ┆ 0   ┆ 179 ┆ 234 ┆ 0   ┆ 626 ┆ 111 ┆ 579 ┆ 544 ┆ 596 ┆ 854 ┆ 654 ┆ 481 ┆ 446 ┆ 278 ┆ 376 ┆ 322 ┆ 314 ┆ 454 ┆ 456 ┆ 0   ┆ 125 ┆ 328 ┆ 288 ┆ 145 ┆ 443 ┆ 47  ┆ 250 ┆ 238 ┆ 36  ┆ 261 ┆ 264 ┆ 269 ┆ 275 ┆ 254 ┆ 279 ┆ 259 ┆ 255 ┆ 151 ┆ 58  ┆ 141 ┆ 158 ┆ 61  ┆ 152 ┆ 154 ┆ 166 ┆ 217 ┆ 182 ┆ 175 ┆ 171 ┆ 172 ┆ 327 ┆ 975 ┆ 0   │
│ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 1   ┆ 0   ┆ 7   ┆ 7   ┆     ┆ 3   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 0   ┆ 6   ┆ 2   ┆     ┆     ┆     ┆ 6   ┆ 7   ┆ 1   ┆ 4   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 69  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 70  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 532 ┆ 0   ┆ 447 ┆ 351 ┆ 744 ┆ 269 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 179 ┆ 184 ┆ 186 ┆ 218 ┆ 213 ┆ 0   ┆ 292 ┆ 523 ┆ 0   ┆ 120 ┆ 175 ┆ 111 ┆ 998 ┆ 112 ┆ 141 ┆ 112 ┆ 835 ┆ 772 ┆ 387 ┆ 531 ┆ 464 ┆ 439 ┆ 774 ┆ 787 ┆ 0   ┆ 222 ┆ 528 ┆ 474 ┆ 252 ┆ 712 ┆ 66  ┆ 468 ┆ 457 ┆ 38  ┆ 454 ┆ 466 ┆ 465 ┆ 477 ┆ 464 ┆ 476 ┆ 473 ┆ 468 ┆ 216 ┆ 148 ┆ 340 ┆ 353 ┆ 129 ┆ 335 ┆ 343 ┆ 368 ┆ 458 ┆ 426 ┆ 380 ┆ 380 ┆ 402 ┆ 649 ┆ 154 ┆ 0   │
│ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 9   ┆ 1   ┆ 3   ┆ 7   ┆     ┆ 7   ┆     ┆     ┆ 9   ┆ 8   ┆ 6   ┆     ┆ 3   ┆ 5   ┆ 6   ┆     ┆     ┆ 0   ┆ 4   ┆ 0   ┆ 7   ┆     ┆     ┆     ┆ 3   ┆ 9   ┆ 2   ┆ 2   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     │
│ 79  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 80  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 299 ┆ 0   ┆ 217 ┆ 185 ┆ 371 ┆ 983 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 774 ┆ 804 ┆ 796 ┆ 865 ┆ 892 ┆ 0   ┆ 117 ┆ 314 ┆ 0   ┆ 654 ┆ 874 ┆ 568 ┆ 504 ┆ 563 ┆ 664 ┆ 545 ┆ 378 ┆ 344 ┆ 137 ┆ 190 ┆ 169 ┆ 148 ┆ 332 ┆ 347 ┆ 0   ┆ 109 ┆ 227 ┆ 192 ┆ 118 ┆ 301 ┆ 36  ┆ 224 ┆ 218 ┆ 34  ┆ 230 ┆ 227 ┆ 229 ┆ 239 ┆ 230 ┆ 231 ┆ 230 ┆ 237 ┆ 931 ┆ 83  ┆ 195 ┆ 195 ┆ 73  ┆ 190 ┆ 188 ┆ 203 ┆ 268 ┆ 240 ┆ 234 ┆ 215 ┆ 236 ┆ 376 ┆ 764 ┆ 0   │
│ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 9   ┆ 0   ┆ 1   ┆     ┆     ┆     ┆ 2   ┆ 7   ┆ 9   ┆ 1   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 89  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 90  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 2   ┆ 5   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 4   ┆ 2   ┆ 2   ┆ 3   ┆ 0   ┆ 5   ┆ 4   ┆ 0   ┆ 4   ┆ 7   ┆ 3   ┆ 4   ┆ 4   ┆ 3   ┆ 3   ┆ 3   ┆ 4   ┆ 7   ┆ 7   ┆ 5   ┆ 7   ┆ 3   ┆ 3   ┆ 0   ┆ 5   ┆ 10  ┆ 4   ┆ 7   ┆ 11  ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 4   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 4   ┆ 0   │
│ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

The following columns are defined in the dictionary with 1 = Yes and 9 = Missing. In these binary indicator fields, it is common data science practice to treat a missing value (9) as a "No" (0), as it implies the patient did not report the condition [Conversation History].
• Arthritis Indicator (ARTHRITIS)
• Cancer Indicator (CANCER)
• Circulation Indicator (CIRCULATION)
• Depression Indicator (DEPRESSION)
• Diabetes Indicator (DIABETES)
• Heart Disease Indicator (HEART_DISEASE)
• High Blood Pressure Indicator (HIGH_BP)
• Kidney Disease Indicator (KIDNEY_DISEASE)
• Liver Disease Indicator (LIVER_DISEASE)
• Lung Disease Indicator (LUNG_DISEASE)
• Nervous System Indicator (NERVOUS_SYSTEM)
• Stroke Indicator (STROKE)

In [ ]:
# Replace missing values (originally 9) with 0 in binary indicator columns
# Already handlled by previous step, but we can verify that all 9s have been replaced
indicator_columns = [
    'Arthritis', 'Cancer', 'Circulation', 'Depression', 'Diabetes',
    'Heart Disease', 'High Bp', 'Kidney Disease', 'Liver Disease',
    'Lung Disease', 'Nervous System', 'Stroke'
]

# Check which indicator columns exist and have null values
existing_cols = [c for c in indicator_columns if c in df.columns]
missing_cols  = [c for c in indicator_columns if c not in df.columns]

if missing_cols:
    print(f"Columns NOT found in dataframe: {missing_cols}")

null_check = df.select(existing_cols).null_count()
print("Null counts for indicator columns:")
print(null_check)

Null counts for indicator columns:
shape: (1, 12)
┌────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ Arthri ┆ Cancer ┆ Circul ┆ Depre ┆ Diabe ┆ Heart ┆ High  ┆ Kidne ┆ Liver ┆ Lung  ┆ Nervo ┆ Strok │
│ tis    ┆ ---    ┆ ation  ┆ ssion ┆ tes   ┆ Disea ┆ Bp    ┆ y Dis ┆ Disea ┆ Disea ┆ us    ┆ e     │
│ ---    ┆ u32    ┆ ---    ┆ ---   ┆ ---   ┆ se    ┆ ---   ┆ ease  ┆ se    ┆ se    ┆ Syste ┆ ---   │
│ u32    ┆        ┆ u32    ┆ u32   ┆ u32   ┆ ---   ┆ u32   ┆ ---   ┆ ---   ┆ ---   ┆ m     ┆ u32   │
│        ┆        ┆        ┆       ┆       ┆ u32   ┆       ┆ u32   ┆ u32   ┆ u32   ┆ ---   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ u32   ┆       │
╞════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 0      ┆ 0      ┆ 0      ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
└────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

Delete patient records where they havent responded for 12 questions related to oxford hop score 

these 12 columns represent the individual dimensions of the Oxford Hip Score (OHS), which is the primary disease-specific measure for hip replacements

We removed observations with missing values" to ensure that the models were trained on fully informative and structured data. By removing rows where these functional questions were skipped, you ensure your model follows a robust real-world benchmark

The sources identify that preoperative Q score dimensions are among the most important predictors for surgical success. Specifically, the question regarding limping (HR_Q1_LIMPING) is cited as a top predictor for postoperative outcomes. Imputing values for such high-impact variables would introduce significant noise and bias, potentially causing the model to misidentify "Non-Responders"

Hip Replacement Pre-Op Q Pain                      0.15
Hip Replacement Pre-Op Q Sudden Pain               0.89
Hip Replacement Pre-Op Q Night Pain                0.86
Hip Replacement Pre-Op Q Washing                   0.11
Hip Replacement Pre-Op Q Transport                 0.90
Hip Replacement Pre-Op Q Dressing                  0.90
Hip Replacement Pre-Op Q Shopping                  0.91
Hip Replacement Pre-Op Q Walking                   0.94
Hip Replacement Pre-Op Q Limping                   0.89
Hip Replacement Pre-Op Q Stairs                    0.93
Hip Replacement Pre-Op Q Standing                  0.91
Hip Replacement Pre-Op Q Work                      0.90

In [20]:
# Remove rows where any of the 12 Hip Replacement Pre-Op Q dimensions have missing values
hr_pre_cols = [col for col in df.columns if col.startswith('Hip Replacement Pre-Op Q') and col != 'Hip Replacement Pre-Op Q Score']

print("Hip Replacement Pre-Op Q columns (excluding Score):", hr_pre_cols)
print("Number of columns:", len(hr_pre_cols))

initial_shape = df.shape
df = df.drop_nulls(subset=hr_pre_cols)
final_shape = df.shape

print(f"Removed {initial_shape[0] - final_shape[0]} rows with missing values in Hip Replacement Pre-Op Q dimensions.")
print(f"New dataframe shape: {final_shape}")

Hip Replacement Pre-Op Q columns (excluding Score): ['Hip Replacement Pre-Op Q Pain', 'Hip Replacement Pre-Op Q Sudden Pain', 'Hip Replacement Pre-Op Q Night Pain', 'Hip Replacement Pre-Op Q Washing', 'Hip Replacement Pre-Op Q Transport', 'Hip Replacement Pre-Op Q Dressing', 'Hip Replacement Pre-Op Q Shopping', 'Hip Replacement Pre-Op Q Walking', 'Hip Replacement Pre-Op Q Limping', 'Hip Replacement Pre-Op Q Stairs', 'Hip Replacement Pre-Op Q Standing', 'Hip Replacement Pre-Op Q Work']
Number of columns: 12
Removed 1417 rows with missing values in Hip Replacement Pre-Op Q dimensions.
New dataframe shape: (123427, 82)


Missing values for Hip Replacement Pre-Op Q Score t0_HR_Score and Hip Replacement Post-Op Q Score t1_HR_Score can be calaculated by adding up the 12 questions
Hip ReplacementScore = It is the sum total of the Oxford Hip Score (OHS), a validated 12-question survey used by the NHS to establish a baseline for patient health

Missing values for Pre-Op Q EQ5D Index Profile can be calculated by concatenating Pre-Op Q Mobility	Pre-Op Q Self-Care	Pre-Op Q Activity	Pre-Op Q Discomfort	Pre-Op Q Anxiety as string

Missing value for post-Op Q EQ5D Index Profile can be calcualted by concatinating Post-Op Q Mobility	Post-Op Q Self-Care	Post-Op Q Activity	Post-Op Q Discomfort	Post-Op Q Anxiety

In [21]:
# Calculate missing values for Hip Replacement Pre-Op Q Score by summing the 12 dimension columns
t0_hr_cols = [col for col in df.columns if col.startswith('Hip Replacement Pre-Op Q') and col != 'Hip Replacement Pre-Op Q Score']

print("Hip Replacement Pre-Op Q columns (excluding Score):", t0_hr_cols)
print("Number of Hip Replacement Pre-Op Q columns:", len(t0_hr_cols))

if len(t0_hr_cols) == 12:
    df = df.with_columns(
        pl.when(pl.col('Hip Replacement Pre-Op Q Score').is_null())
          .then(pl.sum_horizontal([pl.col(c) for c in t0_hr_cols]))
          .otherwise(pl.col('Hip Replacement Pre-Op Q Score'))
          .alias('Hip Replacement Pre-Op Q Score')
    )
    print("Missing values in Hip Replacement Pre-Op Q Score filled by summing the 12 Hip Replacement Pre-Op Q columns.")
else:
    print(f"Warning: Expected 12 Hip Replacement Pre-Op Q columns, but found {len(t0_hr_cols)}.")

Hip Replacement Pre-Op Q columns (excluding Score): ['Hip Replacement Pre-Op Q Pain', 'Hip Replacement Pre-Op Q Sudden Pain', 'Hip Replacement Pre-Op Q Night Pain', 'Hip Replacement Pre-Op Q Washing', 'Hip Replacement Pre-Op Q Transport', 'Hip Replacement Pre-Op Q Dressing', 'Hip Replacement Pre-Op Q Shopping', 'Hip Replacement Pre-Op Q Walking', 'Hip Replacement Pre-Op Q Limping', 'Hip Replacement Pre-Op Q Stairs', 'Hip Replacement Pre-Op Q Standing', 'Hip Replacement Pre-Op Q Work']
Number of Hip Replacement Pre-Op Q columns: 12
Missing values in Hip Replacement Pre-Op Q Score filled by summing the 12 Hip Replacement Pre-Op Q columns.

In [24]:
# Calculate missing values for Hip Replacement Post-Op Q Score by summing the 12 dimension columns
t1_hr_cols = [col for col in df.columns if col.startswith('Hip Replacement Post-Op Q') and col != 'Hip Replacement Post-Op Q Score' and 'Predicted' not in col]

print("Hip Replacement Post-Op Q columns (excluding Score and Predicted):", t1_hr_cols)
print("Number of Hip Replacement Post-Op Q columns:", len(t1_hr_cols))

# Check for nulls in these columns before summing
null_check = df.select(t1_hr_cols).null_count()
print("\nNull counts in Post-Op Q dimension columns:")
print(null_check)

if len(t1_hr_cols) == 12:
    # True for any row where at least one component is null
    has_null = pl.any_horizontal([pl.col(c).is_null() for c in t1_hr_cols])

    df = df.with_columns(
        pl.when(has_null)
          # Any null component → score must be null (partial responses are invalid)
          .then(None)
          .when(pl.col('Hip Replacement Post-Op Q Score').is_null())
          # Score missing but all components present → calculate it
          .then(pl.sum_horizontal([pl.col(c) for c in t1_hr_cols]))
          .otherwise(pl.col('Hip Replacement Post-Op Q Score'))
          .alias('Hip Replacement Post-Op Q Score')
    )
    print("\nPost-Op Q Score: set to null where any component is null; filled by sum where score was missing.")
    print(f"Remaining nulls in Post-Op Q Score: {df['Hip Replacement Post-Op Q Score'].null_count()}")
else:
    print(f"Warning: Expected 12 Hip Replacement Post-Op Q columns, but found {len(t1_hr_cols)}.")

Hip Replacement Post-Op Q columns (excluding Score and Predicted): ['Hip Replacement Post-Op Q Pain', 'Hip Replacement Post-Op Q Sudden Pain', 'Hip Replacement Post-Op Q Night Pain', 'Hip Replacement Post-Op Q Washing', 'Hip Replacement Post-Op Q Transport', 'Hip Replacement Post-Op Q Dressing', 'Hip Replacement Post-Op Q Shopping', 'Hip Replacement Post-Op Q Walking', 'Hip Replacement Post-Op Q Limping', 'Hip Replacement Post-Op Q Stairs', 'Hip Replacement Post-Op Q Standing', 'Hip Replacement Post-Op Q Work']
Number of Hip Replacement Post-Op Q columns: 12

Null counts in Post-Op Q dimension columns:
shape: (1, 12)
┌────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ Hip    ┆ Hip    ┆ Hip    ┆ Hip   ┆ Hip   ┆ Hip   ┆ Hip   ┆ Hip   ┆ Hip   ┆ Hip   ┆ Hip   ┆ Hip   │
│ Replac ┆ Replac ┆ Replac ┆ Repla ┆ Repla ┆ Repla ┆ Repla ┆ Repla ┆ Repla ┆ Repla ┆ Repla ┆ Repla │
│ ement  ┆ ement  ┆ ement  ┆ cemen ┆ cemen ┆ cemen ┆ cemen ┆ cemen ┆ cemen ┆ cemen ┆ cemen ┆ cemen │
│ Post-O ┆ Post-O ┆ Post-O ┆ t Pos ┆ t Pos ┆ t Pos ┆ t Pos ┆ t Pos ┆ t Pos ┆ t Pos ┆ t Pos ┆ t Pos │
│ p Q    ┆ p Q    ┆ p Q    ┆ t-Op  ┆ t-Op  ┆ t-Op  ┆ t-Op  ┆ t-Op  ┆ t-Op  ┆ t-Op  ┆ t-Op  ┆ t-Op  │
│ Pain   ┆ Sudd…  ┆ Nigh…  ┆ Q     ┆ Q     ┆ Q     ┆ Q     ┆ Q     ┆ Q     ┆ Q     ┆ Q     ┆ Q     │
│ ---    ┆ ---    ┆ ---    ┆ Wash… ┆ Tran… ┆ Dres… ┆ Shop… ┆ Walk… ┆ Limp… ┆ Stai… ┆ Stan… ┆ Work  │
│ u32    ┆ u32    ┆ u32    ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│        ┆        ┆        ┆ u32   ┆ u32   ┆ u32   ┆ u32   ┆ u32   ┆ u32   ┆ u32   ┆ u32   ┆ u32   │
╞════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 321    ┆ 770    ┆ 805    ┆ 308   ┆ 787   ┆ 791   ┆ 850   ┆ 1078  ┆ 954   ┆ 913   ┆ 868   ┆ 935   │
└────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

Post-Op Q Score: set to null where any component is null; filled by sum where score was missing.
Remaining nulls in Post-Op Q Score: 1394

 Remove Patient that has not responded to respective questions - 

Pre-Op Q Mobility                                  3.32
Pre-Op Q Self-Care                                 3.38
Pre-Op Q Activity                                  3.44
Pre-Op Q Discomfort                                4.16
Pre-Op Q Anxiety                                   3.88

Post-Op Q Mobility                                 2.11
Post-Op Q Self-Care                                1.92
Post-Op Q Activity                                 2.14
Post-Op Q Discomfort                               2.76
Post-Op Q Anxiety                                  2.18
 
 Loss of Clinical Precision: These dimensions are used to identify "Non-Responders". If you impute a "1" (No Problems) for a patient who actually had severe problems, you introduce noise that can lead the model to wrongly predict that a patient will not reach the Minimal Important Difference (MID).
• Impact on Calculated Index: The EQ-5D Index is calculated by subtracting specific weights from a 1.0 baseline based on these five digits. An imputed value would create a "hallucinated" index score, leading to selection bias.
• Invalid Value Errors: As established in our conversation history, you cannot replace these with 0. The valid range for these dimensions is 1 to 3 (1=No problems, 2=Moderate, 3=Extreme)

In [25]:
# Remove patients that have not responded to EQ-5D questions to avoid noise
eq5d_cols = [
    'Pre-Op Q Mobility', 'Pre-Op Q Self-Care', 'Pre-Op Q Activity', 'Pre-Op Q Discomfort', 'Pre-Op Q Anxiety',
    'Post-Op Q Mobility', 'Post-Op Q Self-Care', 'Post-Op Q Activity', 'Post-Op Q Discomfort', 'Post-Op Q Anxiety'
]

initial_shape = df.shape
df = df.drop_nulls(subset=eq5d_cols)
final_shape = df.shape

print(f"Removed {initial_shape[0] - final_shape[0]} rows with missing values in EQ-5D dimensions.")
print(f"New dataframe shape: {final_shape}")

Removed 11608 rows with missing values in EQ-5D dimensions.
New dataframe shape: (111819, 82)

• Pre-Op Q Assisted (1.08% missing):
    ◦ Dictionary: 1 = Yes, 2 = No, 9 = Missing.
    ◦ Strategy: Since the missingness is tiny, perform Mode Imputation to "2" (No), which is the dominant value in the provided CSV excerpts.

In [28]:
# Mode imputation for Pre-Op Q Assisted — fill missing with 2 (No)
df = df.with_columns(pl.col('Pre-Op Q Assisted').fill_null(2))
print("Missing values in 'Pre-Op Q Assisted' filled with 2 (No).")

Missing values in 'Pre-Op Q Assisted' filled with 2 (No).

Pre-Op Q Symptom Period (0.88% missing):
    ◦ Dictionary: 1 = <1 yr, 2 = 1–5 yrs, 3 = 6–10 yrs, 4 = >10 yrs, 9 = Missing.
    ◦ Strategy: The sources identify Symptom Duration as a strong predictor for postoperative outcomes. Because this is a high-impact variable, do not use mode imputation. Listwise deletion for these specific rows is recommended to avoid introducing noise into a critical predictor

In [ ]:
# Listwise deletion for Pre-Op Q Symptom Period
initial_shape = df.shape
df = df.drop_nulls(subset=['Pre-Op Q Symptom Period'])
final_shape = df.shape

print(f"Removed {initial_shape[0] - final_shape[0]} rows with missing 'Pre-Op Q Symptom Period'.")
print(f"New dataframe shape: {final_shape}")

Removed 696 rows with missing 'Pre-Op Q Symptom Period'.
New dataframe shape: (111123, 82)

Pre-Op Q Previous Surgery (0.73% missing):
    ◦ Dictionary: 1 = Yes, 2 = No, 9 = Missing.
    ◦ Strategy: Given the extremely low missingness, Mode Imputation to "2" (No) is a safe way to preserve the other data points in those rows

In [29]:
# Mode imputation for Pre-Op Q Previous Surgery — fill missing with 2 (No)
df = df.with_columns(pl.col('Pre-Op Q Previous Surgery').fill_null(2))
print("Missing values in 'Pre-Op Q Previous Surgery' filled with 2 (No).")

Missing values in 'Pre-Op Q Previous Surgery' filled with 2 (No).

Pre-Op Q Living Arrangements (1.35% missing):
    ◦ Dictionary: 1 = With family/partner, 2 = Alone, 3 = Nursing home, 4 = Other, 9 = Missing.
    ◦ Strategy: Keep "9" as a distinct category ("Unknown/Not Specified"). In predictive modelling, a patient's choice to skip a question about their home life can sometimes be an informative feature regarding their social support system

In [30]:
# Replace null with 9 to keep Unknown/Not Specified as a distinct category
df = df.with_columns(pl.col('Pre-Op Q Living Arrangements').fill_null(9))
print("Missing values in 'Pre-Op Q Living Arrangements' filled with 9 (Unknown/Not Specified).")

Missing values in 'Pre-Op Q Living Arrangements' filled with 9 (Unknown/Not Specified).

Pre-Op Q Disability (5.88% missing):
Dictionary: 1 = Yes, 2 = No, 9 = Missing.
    ◦ Strategy: This is your highest missingness. Do not replace 9 with 0, as the dictionary defines "2" as the code for "No".
    ◦ Best approach: Treat "9" as a third categorical level ("Not Disclosed"). Patients may hesitate to self-identify as "disabled," and forcing them into "Yes" or "No" would introduce selection bias

In [31]:
# Replace null with 9 to specify Not Disclosed as a distinct category
df = df.with_columns(pl.col('Pre-Op Q Disability').fill_null(9))
print("Missing values in 'Pre-Op Q Disability' filled with 9 (Not Disclosed).")

Missing values in 'Pre-Op Q Disability' filled with 9 (Not Disclosed).

In [32]:
# Function to calculate EQ-5D-5L index from profile using UK value set
def calculate_eq5d_index(profile):
    if profile is None or len(str(profile)) != 5:
        return None
    try:
        digits = [int(d) for d in str(profile)]
        if any(d not in [1, 2, 3] for d in digits):
            return None  # Invalid or missing
    except (ValueError, TypeError):
        return None

    # UK value set weights
    constant   = 0.081
    n3_penalty = 0.269

    dim_weights = {
        0: {'2': 0.069, '3': 0.314},  # Mobility
        1: {'2': 0.104, '3': 0.214},  # Self-care
        2: {'2': 0.036, '3': 0.094},  # Usual activities
        3: {'2': 0.123, '3': 0.386},  # Pain/discomfort
        4: {'2': 0.071, '3': 0.236}   # Anxiety/depression
    }

    total_deduction = constant
    has_level_3 = False

    for i, level in enumerate(digits):
        if level == 2:
            total_deduction += dim_weights[i]['2']
        elif level == 3:
            total_deduction += dim_weights[i]['3']
            has_level_3 = True

    if has_level_3:
        total_deduction += n3_penalty

    return 1.0 - total_deduction

# Verify the EQ-5D index calculation for existing values
df_verify = df.filter(pl.col('Pre-Op Q EQ5D Index').is_not_null())
df_verify = df_verify.with_columns(
    pl.col('Pre-Op Q EQ5D Index Profile')
      .map_elements(calculate_eq5d_index, return_dtype=pl.Float64)
      .alias('calculated_index')
)
df_verify = df_verify.with_columns(
    (pl.col('Pre-Op Q EQ5D Index') - pl.col('calculated_index')).alias('difference')
)

print("Verification of EQ-5D index calculation:")
print(f"Number of non-missing Pre-Op Q EQ5D Index: {df_verify.shape[0]}")
print(f"Mean difference: {df_verify['difference'].mean():.6f}")
print(f"Max difference:  {df_verify['difference'].max():.6f}")
print(f"Min difference:  {df_verify['difference'].min():.6f}")
print(f"Number of exact matches (diff < 1e-6): {(df_verify['difference'].abs() < 1e-6).sum()}")

print("\nFirst 10 examples:")
print(df_verify.select(['Pre-Op Q EQ5D Index Profile', 'Pre-Op Q EQ5D Index', 'calculated_index', 'difference']).head(10))

Verification of EQ-5D index calculation:
Number of non-missing Pre-Op Q EQ5D Index: 111123
Mean difference: 0.000305
Max difference:  0.081000
Min difference:  -0.000000
Number of exact matches (diff < 1e-6): 110704

First 10 examples:
shape: (10, 4)
┌─────────────────────────────┬─────────────────────┬──────────────────┬────────────┐
│ Pre-Op Q EQ5D Index Profile ┆ Pre-Op Q EQ5D Index ┆ calculated_index ┆ difference │
│ ---                         ┆ ---                 ┆ ---              ┆ ---        │
│ u32                         ┆ f32                 ┆ f64              ┆ f64        │
╞═════════════════════════════╪═════════════════════╪══════════════════╪════════════╡
│ 22231                       ┆ 0.05                ┆ 0.06             ┆ -0.00      │
│ 22332                       ┆ -0.07               ┆ -0.07            ┆ -0.00      │
│ 22231                       ┆ 0.05                ┆ 0.06             ┆ -0.00      │
│ 22232                       ┆ -0.02               ┆ -0.02            ┆ -0.00      │
│ 21232                       ┆ 0.09                ┆ 0.09             ┆ -0.00      │
│ 21321                       ┆ 0.36                ┆ 0.36             ┆ -0.00      │
│ 22331                       ┆ -0.00               ┆ -0.00            ┆ -0.00      │
│ 22221                       ┆ 0.59                ┆ 0.59             ┆ 0.00       │
│ 11221                       ┆ 0.76                ┆ 0.76             ┆ -0.00      │
│ 22231                       ┆ 0.05                ┆ 0.06             ┆ -0.00      │
└─────────────────────────────┴─────────────────────┴──────────────────┴────────────┘

The verification output shows that the EQ-5D index calculation formula is correct for the vast majority of cases. Out of 117,824 non-missing t0_EQ5D_Index values:

117,354 (99.6%) are exact matches (difference < 1e-6, likely due to floating-point precision).
The mean difference is negligible (0.00032), and the maximum difference is 0.081, which could be due to rounding in the original data or slight variations in value sets.

In [33]:
# Fill missing Pre-Op Q EQ5D Index Profile by concatenating the 5 EQ5D component columns
eq5d_pre_cols = ['Pre-Op Q Mobility', 'Pre-Op Q Self-Care', 'Pre-Op Q Activity', 'Pre-Op Q Discomfort', 'Pre-Op Q Anxiety']

df = df.with_columns(
    pl.when(pl.col('Pre-Op Q EQ5D Index Profile').is_null())
      .then(pl.concat_str([pl.col(c).cast(pl.Utf8) for c in eq5d_pre_cols], separator=''))
      .otherwise(pl.col('Pre-Op Q EQ5D Index Profile'))
      .alias('Pre-Op Q EQ5D Index Profile')
)
print("Missing values in Pre-Op Q EQ5D Index Profile filled by concatenating the 5 EQ5D components.")

df = df.with_columns(
    pl.when(pl.col('Pre-Op Q EQ5D Index').is_null())
      .then(
          pl.col('Pre-Op Q EQ5D Index Profile')
            .map_elements(calculate_eq5d_index, return_dtype=pl.Float64)
      )
      .otherwise(pl.col('Pre-Op Q EQ5D Index'))
      .alias('Pre-Op Q EQ5D Index')
)
print("Missing values in Pre-Op Q EQ5D Index filled using the calculated index from Pre-Op Q EQ5D Index Profile.")

Missing values in Pre-Op Q EQ5D Index Profile filled by concatenating the 5 EQ5D components.
Missing values in Pre-Op Q EQ5D Index filled using the calculated index from Pre-Op Q EQ5D Index Profile.

In [34]:
# Fill missing Post-Op Q EQ5D Index Profile by concatenating the 5 EQ5D component columns
eq5d_post_cols = ['Post-Op Q Mobility', 'Post-Op Q Self-Care', 'Post-Op Q Activity', 'Post-Op Q Discomfort', 'Post-Op Q Anxiety']

df = df.with_columns(
    pl.when(pl.col('Post-Op Q EQ5D Index Profile').is_null())
      .then(pl.concat_str([pl.col(c).cast(pl.Utf8) for c in eq5d_post_cols], separator=''))
      .otherwise(pl.col('Post-Op Q EQ5D Index Profile'))
      .alias('Post-Op Q EQ5D Index Profile')
)
print("Missing values in Post-Op Q EQ5D Index Profile filled by concatenating the 5 EQ5D components.")

df = df.with_columns(
    pl.when(pl.col('Post-Op Q EQ5D Index').is_null())
      .then(
          pl.col('Post-Op Q EQ5D Index Profile')
            .map_elements(calculate_eq5d_index, return_dtype=pl.Float64)
      )
      .otherwise(pl.col('Post-Op Q EQ5D Index'))
      .alias('Post-Op Q EQ5D Index')
)
print("Missing values in Post-Op Q EQ5D Index filled using the calculated index from Post-Op Q EQ5D Index Profile.")

Missing values in Post-Op Q EQ5D Index Profile filled by concatenating the 5 EQ5D components.
Missing values in Post-Op Q EQ5D Index filled using the calculated index from Post-Op Q EQ5D Index Profile.

Ignore columns -

post operation questions, the colmn with t1 and Q init
Hip Replacement EQ5D Index Post-Op Q Predicted - predicted by liner regression
Hip Replacement OHS Post-Op Q Predicted 
Hip Replacement EQ VAS Post-Op Q Predicted

In [35]:
# Identify columns to remove and keep
all_columns = df.columns  # Polars returns a plain list

# Columns to keep even if they contain 'Post-Op'
keep_post_op = ['Post-Op Q EQ5D Index Profile', 'Post-Op Q EQ5D Index', 'Post-Op Q EQ VAS', 'Post-Op Q HR_Score']

# Remove Post-Op columns (except the specified ones), Predicted columns, and CSVYear
removed_columns = [
    col for col in all_columns
    if ('Post-Op' in col and col not in keep_post_op) or 'Predicted' in col or col == 'CSVYear'
]
kept_columns = [col for col in all_columns if col not in removed_columns]

print("Columns to be removed:")
print(removed_columns)
print(f"\nTotal removed: {len(removed_columns)}")

print("\nColumns to be kept:")
print(kept_columns)
print(f"\nTotal kept: {len(kept_columns)}")

Columns to be removed:
['Post-Op Q Assisted', 'Post-Op Q Assisted By', 'Post-Op Q Living Arrangements', 'Post-Op Q Disability', 'Post-Op Q Mobility', 'Post-Op Q Self-Care', 'Post-Op Q Activity', 'Post-Op Q Discomfort', 'Post-Op Q Anxiety', 'Post-Op Q Satisfaction', 'Post-Op Q Sucess', 'Post-Op Q Allergy', 'Post-Op Q Bleeding', 'Post-Op Q Wound', 'Post-Op Q Urine', 'Post-Op Q Further Surgery', 'Post-Op Q Readmitted', 'Hip Replacement EQ5D Index Post-Op Q Predicted', 'Hip Replacement EQ VAS Post-Op Q Predicted', 'Hip Replacement Post-Op Q Pain', 'Hip Replacement Post-Op Q Sudden Pain', 'Hip Replacement Post-Op Q Night Pain', 'Hip Replacement Post-Op Q Washing', 'Hip Replacement Post-Op Q Transport', 'Hip Replacement Post-Op Q Dressing', 'Hip Replacement Post-Op Q Shopping', 'Hip Replacement Post-Op Q Walking', 'Hip Replacement Post-Op Q Limping', 'Hip Replacement Post-Op Q Stairs', 'Hip Replacement Post-Op Q Standing', 'Hip Replacement Post-Op Q Work', 'Hip Replacement Post-Op Q Score', 'Hip Replacement OHS Post-Op Q Predicted', 'CSVYear']

Total removed: 34

Columns to be kept:
['Provider Code', 'Procedure', 'Revision Flag', 'Year', 'Age Band', 'Gender', 'Pre-Op Q Assisted', 'Pre-Op Q Assisted By', 'Pre-Op Q Symptom Period', 'Pre-Op Q Previous Surgery', 'Pre-Op Q Living Arrangements', 'Pre-Op Q Disability', 'Heart Disease', 'High Bp', 'Stroke', 'Circulation', 'Lung Disease', 'Diabetes', 'Kidney Disease', 'Nervous System', 'Liver Disease', 'Cancer', 'Depression', 'Arthritis', 'Pre-Op Q Mobility', 'Pre-Op Q Self-Care', 'Pre-Op Q Activity', 'Pre-Op Q Discomfort', 'Pre-Op Q Anxiety', 'Pre-Op Q EQ5D Index Profile', 'Pre-Op Q EQ5D Index', 'Post-Op Q EQ5D Index Profile', 'Post-Op Q EQ5D Index', 'Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS', 'Hip Replacement Pre-Op Q Pain', 'Hip Replacement Pre-Op Q Sudden Pain', 'Hip Replacement Pre-Op Q Night Pain', 'Hip Replacement Pre-Op Q Washing', 'Hip Replacement Pre-Op Q Transport', 'Hip Replacement Pre-Op Q Dressing', 'Hip Replacement Pre-Op Q Shopping', 'Hip Replacement Pre-Op Q Walking', 'Hip Replacement Pre-Op Q Limping', 'Hip Replacement Pre-Op Q Stairs', 'Hip Replacement Pre-Op Q Standing', 'Hip Replacement Pre-Op Q Work', 'Hip Replacement Pre-Op Q Score']

Total kept: 48

In [36]:
# Create new dataframe with selected columns
df_selected = df.select(kept_columns)

print("New dataframe created with selected columns.")
print("Shape of new dataframe:", df_selected.shape)
print("Columns in new dataframe:")
print(df_selected.columns)

New dataframe created with selected columns.
Shape of new dataframe: (111123, 48)
Columns in new dataframe:
['Provider Code', 'Procedure', 'Revision Flag', 'Year', 'Age Band', 'Gender', 'Pre-Op Q Assisted', 'Pre-Op Q Assisted By', 'Pre-Op Q Symptom Period', 'Pre-Op Q Previous Surgery', 'Pre-Op Q Living Arrangements', 'Pre-Op Q Disability', 'Heart Disease', 'High Bp', 'Stroke', 'Circulation', 'Lung Disease', 'Diabetes', 'Kidney Disease', 'Nervous System', 'Liver Disease', 'Cancer', 'Depression', 'Arthritis', 'Pre-Op Q Mobility', 'Pre-Op Q Self-Care', 'Pre-Op Q Activity', 'Pre-Op Q Discomfort', 'Pre-Op Q Anxiety', 'Pre-Op Q EQ5D Index Profile', 'Pre-Op Q EQ5D Index', 'Post-Op Q EQ5D Index Profile', 'Post-Op Q EQ5D Index', 'Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS', 'Hip Replacement Pre-Op Q Pain', 'Hip Replacement Pre-Op Q Sudden Pain', 'Hip Replacement Pre-Op Q Night Pain', 'Hip Replacement Pre-Op Q Washing', 'Hip Replacement Pre-Op Q Transport', 'Hip Replacement Pre-Op Q Dressing', 'Hip Replacement Pre-Op Q Shopping', 'Hip Replacement Pre-Op Q Walking', 'Hip Replacement Pre-Op Q Limping', 'Hip Replacement Pre-Op Q Stairs', 'Hip Replacement Pre-Op Q Standing', 'Hip Replacement Pre-Op Q Work', 'Hip Replacement Pre-Op Q Score']

In [37]:
# List columns with missing values in df_selected
null_counts  = df_selected.null_count()
missing_cols = [c for c in df_selected.columns if null_counts[c][0] > 0]

print("Columns with missing values in df_selected:")
print(missing_cols)
print(f"\nTotal columns with missing values: {len(missing_cols)}")

print("\nMissing values count per column:")
print(null_counts.select(missing_cols))

Columns with missing values in df_selected:
['Age Band', 'Gender', 'Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS']

Total columns with missing values: 4

Missing values count per column:
shape: (1, 4)
┌──────────┬────────┬─────────────────┬──────────────────┐
│ Age Band ┆ Gender ┆ Pre-Op Q EQ VAS ┆ Post-Op Q EQ VAS │
│ ---      ┆ ---    ┆ ---             ┆ ---              │
│ u32      ┆ u32    ┆ u32             ┆ u32              │
╞══════════╪════════╪═════════════════╪══════════════════╡
│ 8686     ┆ 8686   ┆ 6372            ┆ 3435             │
└──────────┴────────┴─────────────────┴──────────────────┘

In [40]:
# Listwise deletion for Age Band and Gender — both are critical casemix variables
initial_shape = df_selected.shape
df_final = df_selected.drop_nulls(subset=['Age Band', 'Gender'])
final_shape = df_final.shape

print(f"Removed {initial_shape[0] - final_shape[0]} rows with missing Age Band or Gender.")
print(f"New dataframe shape: {final_shape}")

# Recompute missing counts from df_final
null_counts_final = df_final.null_count()
missing_cols_final = [c for c in df_final.columns if null_counts_final[c][0] > 0]

print(f"\nColumns with missing values in df_final: {missing_cols_final}")
print(f"Total columns with missing values: {len(missing_cols_final)}")
if missing_cols_final:
    print("\nMissing values count per column:")
    print(null_counts_final.select(missing_cols_final))

Removed 8686 rows with missing Age Band or Gender.
New dataframe shape: (102437, 48)

Columns with missing values in df_final: ['Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS']
Total columns with missing values: 2

Missing values count per column:
shape: (1, 2)
┌─────────────────┬──────────────────┐
│ Pre-Op Q EQ VAS ┆ Post-Op Q EQ VAS │
│ ---             ┆ ---              │
│ u32             ┆ u32              │
╞═════════════════╪══════════════════╡
│ 5947            ┆ 3209             │
└─────────────────┴──────────────────┘

In [ ]:
# Drop EQ VAS columns — not used in the model
df_final = df_final.drop(['Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS'])

print(f"Dropped 'Pre-Op Q EQ VAS' and 'Post-Op Q EQ VAS'.")
print(f"Final dataframe shape: {df_final.shape}")

# Recompute missing counts from df_final
null_counts_final = df_final.null_count()
missing_cols_final = [c for c in df_final.columns if null_counts_final[c][0] > 0]

print(f"\nColumns with missing values in df_final: {missing_cols_final}")
print(f"Total columns with missing values: {len(missing_cols_final)}")
if missing_cols_final:
    print("\nMissing values count per column:")
    print(null_counts_final.select(missing_cols_final))

Columns with missing values in df_final: []
Total columns with missing values: 0

In [46]:
# Save the cleaned dataframe to a Parquet file
final_shape = df_final.shape
df_final.write_parquet(f'./data/interim/2.1-Hip-data-preparation-Manual.parquet', compression='gzip')
print(f"Dataframe saved to './data/interim/2.1-Hip-data-preparation-Manual.parquet' with shape {final_shape}")

Dataframe saved to './data/interim/2.1-Hip-data-preparation-Manual.parquet' with shape (102437, 46)

for age band and Gender =

 Listwise Deletion (Removal)
The most robust approach for your machine learning model is to remove these 8,686 observations entirely.
• Methodological Alignment: In the research paper evaluating hip replacements, the researchers explicitly stated: "We removed observations with missing values" to ensure the classifiers were trained on fully informative data.
• Statistical Impact: Deleting 8,686 rows from a total population of 130,945 observations represents a loss of only approximately 6.6% of your data. This is a minor trade-off to ensure your model doesn't attempt to learn patterns from "masked" demographics.
• Avoiding Noise: Since age and gender are important casemix-adjustment variables used by the NHS to predict outcomes, attempting to impute them would introduce significant noise

Confusion Matrix - Find out True Negative

Precison - false Positive

Auroc wirh Precsion and recall curve and select a point.

correlation in EQVAS and OHR
what is percentage of improvement of OHR consider as health gain

Startegy for OHS score -

check if there is an increament from past score + 8 / 6 ( recent studies says 6 )
check if the new score is reaching minimum threashold 26
if yes - then its a success for us

else failure for us.