### Import Packages

In [1]:
import os

import glob

import pandas as pd

import zipfile
from pathlib import Path


import numpy as np
import pickle

### Notebook Settings

In [2]:
# Display Settings for Pandas DataFrames
pd.set_option("display.max_rows", None)         # How many rows to display when printing a DataFrame? None shows all rows.
pd.set_option("display.max_columns", None)      # How many columns to display when printing a DataFrame? None shows all columns.
pd.set_option("display.max_info_columns", 100)  # How many rows to display for .info()?
pd.set_option("display.max_info_rows", 1000000) # How many columns to display for .info()?
pd.set_option("display.precision", 2)           # How many decimals to show when printing a DataFrame?

### glob Function Test

In [3]:
# Find all .zip files recursively in data/external
zip_files = glob.glob('../../data/external/**/*.zip', recursive=True)

print(f"Found {len(zip_files)} zip file(s):")
for zip_file in zip_files:
    print(f"{zip_file}")

Found 27 zip file(s):
../../data/external/data-pack-2018-19/Knee Replacement CCG 1819.csv.zip
../../data/external/data-pack-2018-19/Hip Replacement CCG 1819.csv.zip
../../data/external/data-pack-2018-19/Hip Replacement Provider 1819.csv.zip
../../data/external/data-pack-2018-19/Time Series Hip and Knee Replacement 1819.csv.zip
../../data/external/data-pack-2018-19/ProvComm Hip and Knee Replacement 1819.csv.zip
../../data/external/data-pack-2018-19/PartLink Hip and Knee Replacement 1819.csv.zip
../../data/external/data-pack-2018-19/Key Facts Hip and Knee Replacements 1819.csv.zip
../../data/external/data-pack-2018-19/Knee Replacement Provider 1819.csv.zip
../../data/external/data-pack-2018-19/Equality 1819.csv.zip
../../data/external/data-pack-2017-18/Key Facts Hip and Knee Replacements 1718.csv.zip
../../data/external/data-pack-2017-18/Equality 1718.csv.zip
../../data/external/data-pack-2017-18/Hip Replacements CCG 1718.csv.zip
../../data/external/data-pack-2017-18/PartLink Hip and Knee Replacements 1718.csv.zip
../../data/external/data-pack-2017-18/Knee Replacements Provider 1718.csv.zip
../../data/external/data-pack-2017-18/Knee Replacements CCG 1718.csv.zip
../../data/external/data-pack-2017-18/Time Series 1718.csv.zip
../../data/external/data-pack-2017-18/ProvComm Hip and Knee Replacements 1718.csv.zip
../../data/external/data-pack-2017-18/Hip Replacements Provider 1718.csv.zip
../../data/external/data-pack-2016-17/Hip Replacement Provider 1617.csv.zip
../../data/external/data-pack-2016-17/Time Series Hip and Knee Replacement 1617.csv.zip
../../data/external/data-pack-2016-17/Knee Replacement CCG 1617.csv.zip
../../data/external/data-pack-2016-17/Key Facts Hip and Knee Replacement 1617.csv.zip
../../data/external/data-pack-2016-17/Hip Replacement CCG 1617.csv.zip
../../data/external/data-pack-2016-17/Equality Hip and Knee Replacement 1617.csv.zip
../../data/external/data-pack-2016-17/Knee Replacement Provider 1617.csv.zip
../../data/external/data-pack-2016-17/PartLink Hip and Knee Replacement 1617.csv.zip
../../data/external/data-pack-2016-17/ProvComm Hip and Knee Replacement 1617.csv.zip

### Analyse First Selection

In [4]:
# 1. Define paths
# zip_path = "../../data/external/data-pack-2016-17/Knee Replacement Provider 1617.csv.zip"
# target_csv = "Knee Replacement Provider 1617.csv"


# 2. Open the zip and read the specific CSV
# with zipfile.ZipFile(zip_path, 'r') as z:
#    with z.open(target_csv) as f:
#        df_knee_provider_1617 = pd.read_csv(f)

# Display results
# print(f"Successfully loaded {target_csv}")
# print(df_knee_provider_1617.info())

### Load Files

In [5]:
#1. Define paths
zip_files = [
    "../../data/external/data-pack-2016-17/Knee Replacement Provider 1617.csv.zip",
    "../../data/external/data-pack-2017-18/Knee Replacements Provider 1718.csv.zip",
    "../../data/external/data-pack-2018-19/Knee Replacement Provider 1819.csv.zip",
]
# Select specific CSVs to read from each zip file
target_csv_files = [
    "Knee Replacement Provider 1617.csv",
    "Knee Replacements Provider 1718.csv",
    "Knee Replacement Provider 1819.csv"
]

dataframes = []

for zip_path in zip_files:
    with zipfile.ZipFile(zip_path, 'r') as z:
        for csv_name in target_csv_files:
            if csv_name in z.namelist():
                with z.open(csv_name) as f:
                    df = pd.read_csv(f)
                    dataframes.append(df)
                    print(f"Successfully loaded {target_csv_files} from {zip_path}")
            else:
                print(f"{target_csv_files} not found in {zip_path}")

/var/folders/xk/kg13qzdn74nfkmm57d6yv07m0000gn/T/ipykernel_1859/4261339250.py:21: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

Successfully loaded ['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] from ../../data/external/data-pack-2016-17/Knee Replacement Provider 1617.csv.zip
['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] not found in ../../data/external/data-pack-2016-17/Knee Replacement Provider 1617.csv.zip
['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] not found in ../../data/external/data-pack-2016-17/Knee Replacement Provider 1617.csv.zip
['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] not found in ../../data/external/data-pack-2017-18/Knee Replacements Provider 1718.csv.zip

/var/folders/xk/kg13qzdn74nfkmm57d6yv07m0000gn/T/ipykernel_1859/4261339250.py:21: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

Successfully loaded ['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] from ../../data/external/data-pack-2017-18/Knee Replacements Provider 1718.csv.zip
['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] not found in ../../data/external/data-pack-2017-18/Knee Replacements Provider 1718.csv.zip
['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] not found in ../../data/external/data-pack-2018-19/Knee Replacement Provider 1819.csv.zip
['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] not found in ../../data/external/data-pack-2018-19/Knee Replacement Provider 1819.csv.zip
Successfully loaded ['Knee Replacement Provider 1617.csv', 'Knee Replacements Provider 1718.csv', 'Knee Replacement Provider 1819.csv'] from ../../data/external/data-pack-2018-19/Knee Replacement Provider 1819.csv.zip

/var/folders/xk/kg13qzdn74nfkmm57d6yv07m0000gn/T/ipykernel_1859/4261339250.py:21: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

### Merge & Save File

In [6]:
# Merge all dataframes into a single dataframe
df_prov = pd.concat(dataframes, ignore_index=True)

# Save Output
df_prov.to_csv("df_knee_prov.csv", index=False)

print("Files Merged Successfully and saved as df_prov.csv")

Files Merged Successfully and saved as df_prov.csv

### Create a Copy

In [7]:
df_prov_copy = df_prov.copy(deep=False)

### Descriptive Statistics

Shape of the DataFrame

In [8]:
print("Shape of the merged dataframe:", df_prov.shape)

Shape of the merged dataframe: (139236, 81)

### Data Types

In [9]:
print(df_prov.dtypes)

Provider Code                                        object
Procedure                                            object
Revision Flag                                         int64
Year                                                 object
Age Band                                             object
Gender                                               object
Pre-Op Q Assisted                                     int64
Pre-Op Q Assisted By                                  int64
Pre-Op Q Symptom Period                               int64
Pre-Op Q Previous Surgery                             int64
Pre-Op Q Living Arrangements                          int64
Pre-Op Q Disability                                   int64
Heart Disease                                         int64
High Bp                                               int64
Stroke                                                int64
Circulation                                           int64
Lung Disease                                          int64
Diabetes                                              int64
Kidney Disease                                        int64
Nervous System                                        int64
Liver Disease                                         int64
Cancer                                                int64
Depression                                            int64
Arthritis                                             int64
Pre-Op Q Mobility                                     int64
Pre-Op Q Self-Care                                    int64
Pre-Op Q Activity                                     int64
Pre-Op Q Discomfort                                   int64
Pre-Op Q Anxiety                                      int64
Pre-Op Q EQ5D Index Profile                           int64
Pre-Op Q EQ5D Index                                 float64
Post-Op Q Assisted                                    int64
Post-Op Q Assisted By                                 int64
Post-Op Q Living Arrangements                         int64
Post-Op Q Disability                                  int64
Post-Op Q Mobility                                    int64
Post-Op Q Self-Care                                   int64
Post-Op Q Activity                                    int64
Post-Op Q Discomfort                                  int64
Post-Op Q Anxiety                                     int64
Post-Op Q Satisfaction                                int64
Post-Op Q Sucess                                      int64
Post-Op Q Allergy                                     int64
Post-Op Q Bleeding                                    int64
Post-Op Q Wound                                       int64
Post-Op Q Urine                                       int64
Post-Op Q Further Surgery                             int64
Post-Op Q Readmitted                                  int64
Post-Op Q EQ5D Index Profile                          int64
Post-Op Q EQ5D Index                                float64
Knee Replacement EQ 5D Index Post-Op Q Predicted    float64
Pre-Op Q EQ VAS                                       int64
Post-Op Q EQ VAS                                      int64
Knee Replacement EQ VAS_Post-Op Q Predicted         float64
Knee Replacement Pre-Op Q Pain                        int64
Knee Replacement Pre-Op Q Night Pain                  int64
Knee Replacement Pre-Op Q Washing                     int64
Knee Replacement Pre-Op Q Transport                   int64
Knee Replacement Pre-Op Q Walking                     int64
Knee Replacement Pre-Op Q Standing                    int64
Knee Replacement Pre-Op Q Limping                     int64
Knee Replacement Pre-Op Q Kneeling                    int64
Knee Replacement Pre-Op Q Work                        int64
Knee Replacement Pre-Op Q Confidence                  int64
Knee Replacement Pre-Op Q Shopping                    int64
Knee Replacement Pre-Op Q Stairs                      int64
Knee Replacement Pre-Op Q Score                     float64
Knee Replacement Post-Op Q Pain                       int64
Knee Replacement Post-Op Q Night Pain                 int64
Knee Replacement Post-Op Q Washing                    int64
Knee Replacement Post-Op Q Transport                  int64
Knee Replacement Post-Op Q Walking                    int64
Knee Replacement Post-Op Q Standing                   int64
Knee Replacement Post-Op Q Limping                    int64
Knee Replacement Post-Op Q Kneeling                   int64
Knee Replacement Post-Op Q Work                       int64
Knee Replacement Post-Op Q Confidence                 int64
Knee Replacement Post-Op Q Shopping                   int64
Knee Replacement Post-Op Q Stairs                     int64
Knee Replacement Post-Op Q Score                    float64
Knee Replacement OKS Post-Op Q Predicted            float64
dtype: object

### Analyse Revision Surgery

In [28]:
df_prov["Revision Flag"].value_counts().sort_index()

Revision Flag
0    133962
1      5274
Name: count, dtype: int64

In [ ]:
df_prov["Pre-Op Q Previous Surgery"].value_counts().sort_index()

Pre-Op Q Previous Surgery
1     10784
2    127410
9      1042
Name: count, dtype: int64

### Split into Numerical & String DataFrames

In [10]:
# Create table with numerical data
df_prov_num = df_prov.select_dtypes(include=["number"])

# Column names
l_df_num_names = df_prov_num.columns.tolist()

print(f"We have {len(l_df_num_names)} numerical variables:\n{l_df_num_names}")

We have 76 numerical variables:
['Revision Flag', 'Pre-Op Q Assisted', 'Pre-Op Q Assisted By', 'Pre-Op Q Symptom Period', 'Pre-Op Q Previous Surgery', 'Pre-Op Q Living Arrangements', 'Pre-Op Q Disability', 'Heart Disease', 'High Bp', 'Stroke', 'Circulation', 'Lung Disease', 'Diabetes', 'Kidney Disease', 'Nervous System', 'Liver Disease', 'Cancer', 'Depression', 'Arthritis', 'Pre-Op Q Mobility', 'Pre-Op Q Self-Care', 'Pre-Op Q Activity', 'Pre-Op Q Discomfort', 'Pre-Op Q Anxiety', 'Pre-Op Q EQ5D Index Profile', 'Pre-Op Q EQ5D Index', 'Post-Op Q Assisted', 'Post-Op Q Assisted By', 'Post-Op Q Living Arrangements', 'Post-Op Q Disability', 'Post-Op Q Mobility', 'Post-Op Q Self-Care', 'Post-Op Q Activity', 'Post-Op Q Discomfort', 'Post-Op Q Anxiety', 'Post-Op Q Satisfaction', 'Post-Op Q Sucess', 'Post-Op Q Allergy', 'Post-Op Q Bleeding', 'Post-Op Q Wound', 'Post-Op Q Urine', 'Post-Op Q Further Surgery', 'Post-Op Q Readmitted', 'Post-Op Q EQ5D Index Profile', 'Post-Op Q EQ5D Index', 'Knee Replacement EQ 5D Index Post-Op Q Predicted', 'Pre-Op Q EQ VAS', 'Post-Op Q EQ VAS', 'Knee Replacement EQ VAS_Post-Op Q Predicted', 'Knee Replacement Pre-Op Q Pain', 'Knee Replacement Pre-Op Q Night Pain', 'Knee Replacement Pre-Op Q Washing', 'Knee Replacement Pre-Op Q Transport', 'Knee Replacement Pre-Op Q Walking', 'Knee Replacement Pre-Op Q Standing', 'Knee Replacement Pre-Op Q Limping', 'Knee Replacement Pre-Op Q Kneeling', 'Knee Replacement Pre-Op Q Work', 'Knee Replacement Pre-Op Q Confidence', 'Knee Replacement Pre-Op Q Shopping', 'Knee Replacement Pre-Op Q Stairs', 'Knee Replacement Pre-Op Q Score', 'Knee Replacement Post-Op Q Pain', 'Knee Replacement Post-Op Q Night Pain', 'Knee Replacement Post-Op Q Washing', 'Knee Replacement Post-Op Q Transport', 'Knee Replacement Post-Op Q Walking', 'Knee Replacement Post-Op Q Standing', 'Knee Replacement Post-Op Q Limping', 'Knee Replacement Post-Op Q Kneeling', 'Knee Replacement Post-Op Q Work', 'Knee Replacement Post-Op Q Confidence', 'Knee Replacement Post-Op Q Shopping', 'Knee Replacement Post-Op Q Stairs', 'Knee Replacement Post-Op Q Score', 'Knee Replacement OKS Post-Op Q Predicted']

In [11]:
# Create table with string data
df_prov_str = df_prov.select_dtypes(include=["object"])

# Column names
l_df_str_names = df_prov_str.columns.tolist()

print(f"We have {len(l_df_str_names)} string variables:\n{l_df_str_names}")

We have 5 string variables:
['Provider Code', 'Procedure', 'Year', 'Age Band', 'Gender']

CHECK: Is Gender a String Variable?

### Cross-Check!!!

In [12]:
print(
    f"The original data has  {df_prov.shape[1]} columns. The number and string data" 
    f"have total of {df_prov_num.shape[1] + df_prov_str.shape[1]} columns."
)

The original data has  81 columns. The number and string datahave total of 81 columns.

In [13]:
print(f"The number of obeservations: {df_prov.shape[0]}")

The number of obeservations: 139236

In [14]:
n_obs = df_prov.shape[0]

### Check Missing Variables

#### Numerical Check

In [15]:
df_prov_missing_data_num = (
    
    pd.DataFrame({

        'data_type':    df_prov_num.dtypes,
        'missing':      df_prov_num.isnull().sum()   
    })

    # Add complete%
    .assign(
        missing_pct = lambda x: round(100 * x['missing'] / n_obs, 2),
        complete_pct = lambda x: round(100 * (n_obs - x['missing']) / n_obs, 2)
    )

    # Remove variables that are complete.
    .query("complete_pct < 100")

    # Sort table by data completeness in descending order.
    .sort_values(by = 'complete_pct')
)

df_prov_missing_data_num

,data_type,missing,missing_pct,complete_pct
Knee Replacement EQ VAS_Post-Op Q Predicted,float64,19423,13.95,86.05
Knee Replacement EQ 5D Index Post-Op Q Predicted,float64,14322,10.29,89.71
Pre-Op Q EQ5D Index,float64,7500,5.39,94.61
Post-Op Q EQ5D Index,float64,6274,4.51,95.49
Knee Replacement OKS Post-Op Q Predicted,float64,5381,3.86,96.14
Knee Replacement Post-Op Q Score,float64,2579,1.85,98.15
Knee Replacement Pre-Op Q Score,float64,1669,1.20,98.80

#### String Check

In [16]:
# Pandas.
df_prov_missing_data_str = (
    
    pd.DataFrame({

        'data_type':    df_prov_str.dtypes,
        'missing':      df_prov_str.isnull().sum()   
    })

    # Add complete%
    .assign(
        complete_pct = lambda x: round(100 * (n_obs - x['missing']) / n_obs, 2)
    )

    # Remove variables that are complete.
    #.query("complete_pct < 100")

    # Sort table by number of missing data in descending order.
    .sort_values(
        by        = 'complete_pct',
        ascending = False
    )
)

df_prov_missing_data_str

              data_type  missing  complete_pct
Provider Code    object        0         100.0
Procedure        object        0         100.0
Year             object        0         100.0
Age Band         object        0         100.0
Gender           object        0         100.0

### Delete Redundant Columns

### Descriptive Statistics

#### Numeric Statistics

In [17]:
df_prov_num.describe()

,Revision Flag,Pre-Op Q Assisted,Pre-Op Q Assisted By,Pre-Op Q Symptom Period,Pre-Op Q Previous Surgery,Pre-Op Q Living Arrangements,Pre-Op Q Disability,Heart Disease,High Bp,Stroke,Circulation,Lung Disease,Diabetes,Kidney Disease,Nervous System,Liver Disease,Cancer,Depression,Arthritis,Pre-Op Q Mobility,Pre-Op Q Self-Care,Pre-Op Q Activity,Pre-Op Q Discomfort,Pre-Op Q Anxiety,Pre-Op Q EQ5D Index Profile,Pre-Op Q EQ5D Index,Post-Op Q Assisted,Post-Op Q Assisted By,Post-Op Q Living Arrangements,Post-Op Q Disability,Post-Op Q Mobility,Post-Op Q Self-Care,Post-Op Q Activity,Post-Op Q Discomfort,Post-Op Q Anxiety,Post-Op Q Satisfaction,Post-Op Q Sucess,Post-Op Q Allergy,Post-Op Q Bleeding,Post-Op Q Wound,Post-Op Q Urine,Post-Op Q Further Surgery,Post-Op Q Readmitted,Post-Op Q EQ5D Index Profile,Post-Op Q EQ5D Index,Knee Replacement EQ 5D Index Post-Op Q Predicted,Pre-Op Q EQ VAS,Post-Op Q EQ VAS,Knee Replacement EQ VAS_Post-Op Q Predicted,Knee Replacement Pre-Op Q Pain,Knee Replacement Pre-Op Q Night Pain,Knee Replacement Pre-Op Q Washing,Knee Replacement Pre-Op Q Transport,Knee Replacement Pre-Op Q Walking,Knee Replacement Pre-Op Q Standing,Knee Replacement Pre-Op Q Limping,Knee Replacement Pre-Op Q Kneeling,Knee Replacement Pre-Op Q Work,Knee Replacement Pre-Op Q Confidence,Knee Replacement Pre-Op Q Shopping,Knee Replacement Pre-Op Q Stairs,Knee Replacement Pre-Op Q Score,Knee Replacement Post-Op Q Pain,Knee Replacement Post-Op Q Night Pain,Knee Replacement Post-Op Q Washing,Knee Replacement Post-Op Q Transport,Knee Replacement Post-Op Q Walking,Knee Replacement Post-Op Q Standing,Knee Replacement Post-Op Q Limping,Knee Replacement Post-Op Q Kneeling,Knee Replacement Post-Op Q Work,Knee Replacement Post-Op Q Confidence,Knee Replacement Post-Op Q Shopping,Knee Replacement Post-Op Q Stairs,Knee Replacement Post-Op Q Score,Knee Replacement OKS Post-Op Q Predicted
count,139236.00,139236.00,139236.0,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,131736.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,132962.00,124914.00,139236.00,139236.00,119813.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,137567.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,139236.00,136657.00,133855.00
mean,0.04,1.92,0.0,2.65,1.97,1.35,1.81,8.25,5.46,8.87,8.55,8.27,8.00,8.84,8.92,8.95,8.57,8.25,2.84,2.14,1.55,2.26,2.64,1.68,23214.76,0.41,2.01,8.41,1.41,1.93,1.61,1.32,1.70,1.87,1.42,2.36,1.53,2.53,2.80,2.64,2.68,2.06,2.02,17587.27,0.75,0.72,154.01,118.23,72.58,0.58,1.30,2.82,2.13,2.12,1.75,0.97,0.90,1.49,1.91,1.91,1.85,18.98,2.67,2.85,3.62,3.11,3.39,3.12,3.12,1.65,3.09,3.53,3.21,3.06,35.89,34.43
std,0.19,0.82,0.0,1.05,0.67,1.04,1.59,2.33,3.97,1.02,1.85,2.31,2.64,1.13,0.80,0.61,1.81,2.33,3.36,1.25,1.43,1.31,1.39,1.54,13893.51,0.31,0.79,2.05,1.20,1.47,1.20,1.15,1.23,1.34,1.25,1.33,1.23,2.08,2.34,2.21,2.26,0.81,0.85,12939.07,0.25,0.12,271.43,196.45,9.46,0.72,1.37,1.02,1.07,1.30,1.11,1.29,1.18,1.14,1.36,1.39,1.14,7.75,1.29,1.34,0.90,1.06,1.13,1.03,1.21,1.48,1.11,0.95,1.29,1.14,9.47,4.74
min,0.00,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,11111.00,-0.59,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,11111.00,-0.59,0.03,0.00,0.00,21.76,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,7.06
25%,0.00,2.00,0.0,2.00,2.00,1.00,1.00,9.00,1.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,1.00,2.00,1.00,2.00,2.00,1.00,21221.00,0.09,2.00,9.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,2.00,2.00,2.00,2.00,2.00,11111.00,0.69,0.65,55.00,69.00,65.96,0.00,0.00,2.00,2.00,2.00,1.00,0.00,0.00,1.00,1.00,1.00,1.00,13.00,2.00,2.00,3.00,2.00,3.00,3.00,3.00,0.00,2.00,3.00,3.00,2.00,30.00,31.55
50%,0.00,2.00,0.0,2.00,2.00,1.00,2.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,1.00,2.00,1.00,2.00,2.00,1.00,21231.00,0.59,2.00,9.00,1.00,2.00,1.00,1.00,2.00,2.00,1.00,2.00,1.00,2.00,2.00,2.00,2.00,2.00,2.00,11221.00,0.76,0.74,75.00,80.00,73.17,0.00,1.00,3.00,2.00,2.00,2.00,1.00,1.00,1.00,2.00,2.00,2.00,19.00,3.00,3.00,4.00,3.00,4.00,3.00,3.00,2.00,3.00,4.00,4.00,3.00,38.00,35.07
75%,0.00,2.00,0.0,3.00,2.00,1.00,2.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,1.00,2.00,2.00,2.00,3.00,2.00,22222.00,0.69,2.00,9.00,2.00,2.00,2.00,1.00,2.00,2.00,1.00,3.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,21221.00,1.00,0.82,89.00,90.00,79.81,1.00,2.00,4.00,2.00,3.00,2.00,1.00,1.00,2.00,3.00,3.00,2.00,24.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,3.00,4.00,4.00,4.00,4.00,43.00,38.00
max,1.00,9.00,0.0,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,99999.00,1.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,99999.00,1.00,1.00,999.00,999.00,93.99,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,48.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,48.00,48.00

#### String Statistics

In [18]:
df_prov_str.describe()

       Provider Code         Procedure     Year  Age Band  Gender
count         139236            139236   139236    139236  139236
unique           294                 1        3         7       5
top              RL1  Knee Replacement  2016/17  70 to 79       2
freq            3135            139236    47604     55056   65647

!!! EXTRA: Consider developing f_describe (utils package)

### Concatenate numerical & string data frames

In [19]:
df_prov_imp = pd.concat([df_prov_num, df_prov_str], axis=1)

print(df_prov_imp.shape)

(139236, 81)

### Visualize Data Frame

In [20]:
# print(df_prov_imp)

### Rescaling - Standardization

In [21]:
df_prov_imp.replace({9: np.nan, "*": np.nan, "": np.nan, 999: np.nan}, inplace=True)

In [22]:
total_missing = df_prov_imp.isna().sum().sum()
print(f'Total missing cells after standardisation: {total_missing:,}')

Total missing cells after standardisation: 1,807,003

### Impute Missing Data: Comorbidity Flags

In [23]:
comorb_cols = [
    "Arthritis", "Cancer", "Circulation", "Depression", "Diabetes",
    "Heart Disease", "High Bp", "Kidney Disease", "Liver Disease",
    "Lung Disease", "Nervous System", "Stroke"
]

# For comorbidities, 9 = not recorded → treat as 0 (no comorbidity)
for col in comorb_cols:
    df_prov_imp[col] = df_prov_imp[col].fillna(0).astype(int)

### Impute Pre-Op Assisted

### OKS Pre-Op Items

Decide if we want to impute or delete!

In [24]:
df_prov_imp.head(100)

,Revision Flag,Pre-Op Q Assisted,Pre-Op Q Assisted By,Pre-Op Q Symptom Period,Pre-Op Q Previous Surgery,Pre-Op Q Living Arrangements,Pre-Op Q Disability,Heart Disease,High Bp,Stroke,Circulation,Lung Disease,Diabetes,Kidney Disease,Nervous System,Liver Disease,Cancer,Depression,Arthritis,Pre-Op Q Mobility,Pre-Op Q Self-Care,Pre-Op Q Activity,Pre-Op Q Discomfort,Pre-Op Q Anxiety,Pre-Op Q EQ5D Index Profile,Pre-Op Q EQ5D Index,Post-Op Q Assisted,Post-Op Q Assisted By,Post-Op Q Living Arrangements,Post-Op Q Disability,Post-Op Q Mobility,Post-Op Q Self-Care,Post-Op Q Activity,Post-Op Q Discomfort,Post-Op Q Anxiety,Post-Op Q Satisfaction,Post-Op Q Sucess,Post-Op Q Allergy,Post-Op Q Bleeding,Post-Op Q Wound,Post-Op Q Urine,Post-Op Q Further Surgery,Post-Op Q Readmitted,Post-Op Q EQ5D Index Profile,Post-Op Q EQ5D Index,Knee Replacement EQ 5D Index Post-Op Q Predicted,Pre-Op Q EQ VAS,Post-Op Q EQ VAS,Knee Replacement EQ VAS_Post-Op Q Predicted,Knee Replacement Pre-Op Q Pain,Knee Replacement Pre-Op Q Night Pain,Knee Replacement Pre-Op Q Washing,Knee Replacement Pre-Op Q Transport,Knee Replacement Pre-Op Q Walking,Knee Replacement Pre-Op Q Standing,Knee Replacement Pre-Op Q Limping,Knee Replacement Pre-Op Q Kneeling,Knee Replacement Pre-Op Q Work,Knee Replacement Pre-Op Q Confidence,Knee Replacement Pre-Op Q Shopping,Knee Replacement Pre-Op Q Stairs,Knee Replacement Pre-Op Q Score,Knee Replacement Post-Op Q Pain,Knee Replacement Post-Op Q Night Pain,Knee Replacement Post-Op Q Washing,Knee Replacement Post-Op Q Transport,Knee Replacement Post-Op Q Walking,Knee Replacement Post-Op Q Standing,Knee Replacement Post-Op Q Limping,Knee Replacement Post-Op Q Kneeling,Knee Replacement Post-Op Q Work,Knee Replacement Post-Op Q Confidence,Knee Replacement Post-Op Q Shopping,Knee Replacement Post-Op Q Stairs,Knee Replacement Post-Op Q Score,Knee Replacement OKS Post-Op Q Predicted,Provider Code,Procedure,Year,Age Band,Gender
0,0,2.0,0,4.0,2.0,2.0,1.0,0,0,0,0,0,0,0,0,0,0,1,0,2.0,2.0,2.0,3.0,2.0,22232,-1.60e-02,2.0,NaN,2.0,1.0,2.0,NaN,2.0,2.0,3.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,29223,NaN,NaN,63.0,50.0,59.82,0.0,0.0,2.0,3.0,2.0,1.0,0.0,0.0,1.0,2.0,2.0,2.0,15.0,3.0,2.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,1.0,3.0,2.0,29.0,28.12,ADP02,Knee Replacement,2016/17,NaN,NaN
1,0,2.0,0,1.0,2.0,2.0,2.0,0,0,0,0,0,0,0,0,0,0,1,0,2.0,2.0,3.0,2.0,2.0,22322,1.89e-01,2.0,NaN,2.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,11222,0.69,0.67,30.0,58.0,64.73,3.0,2.0,4.0,3.0,4.0,3.0,1.0,1.0,1.0,3.0,2.0,3.0,30.0,4.0,1.0,3.0,2.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,3.0,39.0,39.59,ADP02,Knee Replacement,2016/17,NaN,NaN
2,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,3.0,3.0,1.0,21331,1.01e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.79,65.0,80.0,77.92,0.0,1.0,4.0,2.0,2.0,1.0,2.0,3.0,1.0,3.0,2.0,3.0,24.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,45.0,40.25,ADP02,Knee Replacement,2016/17,NaN,NaN
3,0,2.0,0,2.0,2.0,1.0,1.0,1,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11121,0.80,0.79,90.0,90.0,79.59,1.0,3.0,3.0,2.0,4.0,2.0,2.0,2.0,2.0,0.0,3.0,3.0,27.0,3.0,2.0,4.0,3.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,43.0,37.90,ADP02,Knee Replacement,2016/17,NaN,NaN
4,0,1.0,0,3.0,2.0,1.0,1.0,0,1,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,21221,0.69,0.82,95.0,NaN,NaN,1.0,4.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,2.0,4.0,32.0,3.0,4.0,4.0,3.0,3.0,4.0,2.0,2.0,2.0,4.0,2.0,3.0,36.0,40.14,ADP02,Knee Replacement,2016/17,NaN,NaN
5,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,2.0,1.0,1.0,2.0,1.0,21121,7.27e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.89,90.0,85.0,87.14,1.0,2.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,34.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,46.0,41.96,ADP02,Knee Replacement,2016/17,NaN,NaN
6,0,2.0,0,2.0,2.0,2.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,1.0,2.0,1.0,21121,7.27e-01,2.0,NaN,2.0,2.0,1.0,1.0,1.0,2.0,1.0,4.0,3.0,1.0,2.0,2.0,1.0,2.0,2.0,11121,0.80,0.89,75.0,60.0,80.63,1.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,4.0,4.0,3.0,2.0,3.0,0.0,3.0,3.0,3.0,2.0,29.0,NaN,ADP02,Knee Replacement,2016/17,NaN,NaN
7,0,2.0,0,3.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.90,89.0,90.0,86.89,1.0,2.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,2.0,2.0,1.0,23.0,2.0,4.0,4.0,3.0,4.0,4.0,3.0,3.0,4.0,3.0,4.0,3.0,41.0,39.84,ADP02,Knee Replacement,2016/17,NaN,NaN
8,0,2.0,0,2.0,2.0,1.0,2.0,0,1,0,0,0,0,0,0,0,0,0,0,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,11111,1.00,0.90,85.0,95.0,84.85,1.0,4.0,2.0,2.0,3.0,3.0,2.0,2.0,2.0,4.0,2.0,2.0,29.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,4.0,46.0,41.54,ADP02,Knee Replacement,2016/17,NaN,NaN
9,0,2.0,0,3.0,2.0,1.0,2.0,0,1,0,0,1,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,99999,NaN,NaN,75.0,NaN,NaN,0.0,2.0,2.0,2.0,1.0,2.0,1.0,0.0,2.0,2.0,2.0,3.0,19.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,45.0,37.18,AHH,Knee Replacement,2016/17,NaN,NaN
10,0,1.0,0,1.0,2.0,2.0,1.0,0,1,0,0,1,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,99999,NaN,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11211,0.88,NaN,NaN,65.0,NaN,1.0,4.0,4.0,2.0,3.0,4.0,3.0,2.0,3.0,3.0,2.0,2.0,33.0,4.0,4.0,4.0,3.0,4.0,4.0,3.0,3.0,4.0,4.0,3.0,3.0,43.0,37.59,AHH,Knee Replacement,2016/17,NaN,NaN
11,0,2.0,0,2.0,2.0,1.0,1.0,0,1,0,0,0,0,0,0,0,1,0,1,2.0,1.0,3.0,3.0,2.0,21332,3.00e-02,2.0,NaN,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,21121,0.73,0.63,39.0,95.0,62.82,0.0,2.0,2.0,1.0,2.0,1.0,0.0,1.0,0.0,3.0,0.0,1.0,13.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,4.0,46.0,32.18,AHH,Knee Replacement,2016/17,NaN,NaN
12,0,2.0,0,2.0,2.0,2.0,1.0,0,1,0,0,0,0,0,0,0,0,0,0,2.0,1.0,2.0,3.0,2.0,21232,8.80e-02,2.0,6.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,11221,0.76,0.66,60.0,40.0,68.28,0.0,0.0,3.0,1.0,3.0,1.0,1.0,1.0,0.0,2.0,1.0,2.0,15.0,1.0,1.0,4.0,2.0,4.0,2.0,2.0,0.0,3.0,2.0,2.0,2.0,25.0,33.41,AHH,Knee Replacement,2016/17,NaN,NaN
13,0,2.0,0,1.0,2.0,1.0,1.0,0,1,0,0,0,0,0,0,0,0,0,1,2.0,2.0,2.0,3.0,2.0,22232,-1.60e-02,2.0,NaN,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,21221,0.69,0.66,35.0,70.0,64.38,0.0,0.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,12.0,2.0,2.0,4.0,2.0,3.0,3.0,2.0,1.0,2.0,3.0,3.0,3.0,30.0,32.60,AHH,Knee Replacement,2016/17,NaN,NaN
14,0,2.0,0,3.0,2.0,2.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,3.0,2.0,1.0,11321,4.33e-01,2.0,NaN,1.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11311,0.56,0.74,80.0,100.0,79.49,1.0,3.0,4.0,3.0,4.0,3.0,1.0,2.0,1.0,3.0,2.0,2.0,29.0,3.0,2.0,4.0,4.0,4.0,4.0,4.0,0.0,0.0,4.0,4.0,4.0,37.0,38.77,AHH,Knee Replacement,2016/17,NaN,NaN
15,0,2.0,0,3.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,2.0,2.0,3.0,1.0,22231,5.50e-02,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.77,88.0,85.0,87.64,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,47.0,31.12,AHH,Knee Replacement,2016/17,NaN,NaN
16,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,3.0,1.0,21231,1.59e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11121,0.80,0.79,NaN,68.0,NaN,0.0,1.0,4.0,2.0,2.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,15.0,2.0,2.0,4.0,4.0,4.0,3.0,3.0,1.0,2.0,4.0,4.0,3.0,36.0,36.56,AHH,Knee Replacement,2016/17,NaN,NaN
17,0,2.0,0,1.0,2.0,1.0,2.0,0,0,0,0,0,0,1,0,0,1,0,1,2.0,1.0,2.0,2.0,2.0,21222,6.20e-01,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.80,NaN,80.0,NaN,0.0,0.0,2.0,1.0,2.0,1.0,0.0,0.0,1.0,2.0,2.0,1.0,12.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,48.0,32.95,AHH,Knee Replacement,2016/17,NaN,NaN
18,0,2.0,0,4.0,2.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,2.0,1.0,1.0,2.0,1.0,21121,7.27e-01,2.0,NaN,1.0,1.0,2.0,2.0,3.0,2.0,2.0,5.0,5.0,NaN,NaN,1.0,NaN,1.0,1.0,22322,0.19,0.82,NaN,23.0,NaN,0.0,4.0,4.0,4.0,0.0,1.0,1.0,1.0,2.0,4.0,4.0,3.0,28.0,1.0,2.0,2.0,1.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,10.0,38.78,AHH,Knee Replacement,2016/17,NaN,NaN
19,0,2.0,0,4.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11121,0.80,0.84,80.0,80.0,82.11,1.0,0.0,3.0,2.0,3.0,1.0,1.0,1.0,2.0,3.0,3.0,2.0,22.0,3.0,3.0,4.0,3.0,4.0,3.0,4.0,3.0,3.0,4.0,4.0,4.0,42.0,38.35,AHH,Knee Replacement,2016/17,NaN,NaN
20,0,1.0,0,2.0,2.0,2.0,2.0,0,1,0,0,0,1,0,0,0,0,0,1,2.0,1.0,2.0,2.0,2.0,21222,6.20e-01,2.0,NaN,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.85,80.0,80.0,80.25,1.0,4.0,4.0,4.0,2.0,4.0,1.0,3.0,1.0,3.0,3.0,4.0,34.0,4.0,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AHH,Knee Replacement,2016/17,NaN,NaN
21,0,2.0,0,2.0,2.0,1.0,NaN,0,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,2.0,21222,6.20e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11121,0.80,0.86,83.0,90.0,84.29,1.0,4.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,28.0,3.0,4.0,4.0,3.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,44.0,40.86,AHH,Knee Replacement,2016/17,NaN,NaN
22,0,2.0,0,1.0,2.0,2.0,2.0,0,1,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11112,0.85,0.87,60.0,NaN,NaN,1.0,1.0,3.0,2.0,3.0,3.0,0.0,0.0,3.0,2.0,3.0,2.0,23.0,4.0,4.0,4.0,3.0,4.0,3.0,4.0,0.0,4.0,4.0,4.0,3.0,41.0,39.09,AHH,Knee Replacement,2016/17,NaN,NaN
23,0,1.0,0,2.0,2.0,1.0,2.0,0,1,0,0,0,1,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,3.0,3.0,NaN,1.0,NaN,NaN,1.0,1.0,21221,0.69,0.87,90.0,90.0,85.26,2.0,2.0,4.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,3.0,3.0,32.0,2.0,3.0,4.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,33.0,41.34,AHH,Knee Replacement,2016/17,NaN,NaN
24,0,1.0,0,4.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,2.0,2.0,1.0,11221,7.60e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,11111,1.00,0.91,70.0,85.0,79.78,1.0,3.0,3.0,3.0,2.0,2.0,0.0,2.0,2.0,1.0,2.0,2.0,23.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,47.0,40.44,AHH,Knee Replacement,2016/17,NaN,NaN
25,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,1,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11221,0.76,0.91,90.0,90.0,87.45,1.0,0.0,4.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,25.0,2.0,1.0,4.0,3.0,4.0,3.0,3.0,1.0,3.0,4.0,4.0,2.0,34.0,41.12,AHH,Knee Replacement,2016/17,NaN,NaN
26,0,2.0,0,3.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,2.0,2.0,1.0,11221,7.60e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.91,80.0,NaN,NaN,1.0,2.0,4.0,2.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,31.0,3.0,3.0,4.0,4.0,4.0,4.0,3.0,2.0,4.0,4.0,4.0,4.0,43.0,42.09,AHH,Knee Replacement,2016/17,NaN,NaN
27,0,1.0,0,2.0,2.0,1.0,1.0,0,1,0,1,0,1,0,0,0,0,0,1,2.0,2.0,2.0,3.0,2.0,22232,-1.60e-02,1.0,1.0,1.0,1.0,NaN,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,91121,NaN,NaN,82.0,85.0,66.03,0.0,0.0,1.0,1.0,2.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,NaN,1.0,2.0,4.0,3.0,3.0,3.0,3.0,0.0,3.0,4.0,4.0,3.0,33.0,26.09,NN401,Knee Replacement,2016/17,NaN,NaN
28,0,2.0,0,2.0,2.0,2.0,1.0,0,1,0,1,0,0,0,0,0,0,0,1,2.0,2.0,2.0,2.0,3.0,22223,8.20e-02,2.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,5.0,4.0,2.0,2.0,2.0,2.0,2.0,1.0,22222,0.52,0.51,NaN,50.0,NaN,2.0,2.0,4.0,2.0,3.0,3.0,3.0,0.0,2.0,0.0,2.0,0.0,23.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,2.0,4.0,2.0,1.0,23.0,30.85,NN401,Knee Replacement,2016/17,NaN,NaN
29,0,2.0,0,2.0,2.0,2.0,1.0,0,1,0,0,0,0,0,0,0,0,0,1,2.0,2.0,2.0,2.0,2.0,22222,5.16e-01,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,21221,0.69,0.71,60.0,90.0,67.06,0.0,0.0,2.0,2.0,0.0,1.0,0.0,0.0,2.0,1.0,2.0,1.0,11.0,2.0,2.0,4.0,3.0,3.0,3.0,0.0,0.0,3.0,4.0,3.0,3.0,30.0,30.50,NN401,Knee Replacement,2016/17,NaN,NaN
30,0,2.0,0,2.0,2.0,1.0,2.0,0,1,0,0,0,0,0,0,0,0,1,1,1.0,1.0,3.0,2.0,2.0,11322,3.62e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11112,0.85,0.72,95.0,90.0,84.11,0.0,0.0,4.0,2.0,3.0,1.0,1.0,1.0,2.0,2.0,2.0,3.0,21.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.0,4.0,4.0,4.0,4.0,43.0,37.24,NN401,Knee Replacement,2016/17,NaN,NaN
31,0,1.0,0,2.0,2.0,1.0,1.0,0,0,0,0,0,1,0,0,0,0,0,1,2.0,1.0,2.0,2.0,2.0,21222,6.20e-01,2.0,NaN,1.0,1.0,1.0,1.0,1.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,11121,0.80,0.73,50.0,70.0,61.63,1.0,2.0,2.0,1.0,3.0,2.0,0.0,0.0,2.0,1.0,1.0,1.0,16.0,3.0,4.0,4.0,3.0,4.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,37.0,31.42,NN401,Knee Replacement,2016/17,NaN,NaN
32,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,1,0,2.0,1.0,2.0,2.0,2.0,21222,6.20e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.73,60.0,75.0,70.01,1.0,4.0,3.0,3.0,2.0,2.0,0.0,2.0,2.0,1.0,2.0,2.0,24.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,3.0,44.0,37.16,NN401,Knee Replacement,2016/17,NaN,NaN
33,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,2.0,2.0,3.0,2.0,22232,-1.60e-02,2.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11121,0.80,0.75,80.0,75.0,83.83,0.0,0.0,1.0,2.0,4.0,1.0,0.0,1.0,1.0,1.0,1.0,2.0,14.0,2.0,3.0,4.0,2.0,4.0,2.0,2.0,3.0,2.0,3.0,3.0,3.0,33.0,36.37,NN401,Knee Replacement,2016/17,NaN,NaN
34,0,2.0,0,2.0,2.0,1.0,2.0,0,1,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,3.0,2.0,21232,8.80e-02,2.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,4.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,21221,0.69,0.76,69.0,60.0,78.15,0.0,2.0,3.0,2.0,2.0,3.0,0.0,1.0,1.0,1.0,2.0,2.0,19.0,1.0,3.0,4.0,4.0,2.0,3.0,1.0,1.0,3.0,3.0,4.0,3.0,32.0,37.75,NN401,Knee Replacement,2016/17,NaN,NaN
35,0,2.0,0,3.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,2.0,1.0,3.0,3.0,1.0,21331,1.01e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,11111,1.00,0.77,95.0,100.0,89.02,0.0,0.0,2.0,2.0,2.0,2.0,0.0,1.0,1.0,1.0,1.0,1.0,13.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,4.0,46.0,35.03,NN401,Knee Replacement,2016/17,NaN,NaN
36,0,2.0,0,4.0,2.0,1.0,1.0,0,0,0,0,1,0,0,0,0,0,0,0,2.0,2.0,2.0,2.0,1.0,22221,5.87e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11121,0.80,0.77,60.0,70.0,67.37,1.0,0.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,19.0,3.0,2.0,4.0,3.0,4.0,4.0,4.0,2.0,3.0,4.0,4.0,4.0,41.0,35.51,NN401,Knee Replacement,2016/17,NaN,NaN
37,0,2.0,0,3.0,2.0,1.0,2.0,0,0,0,0,1,0,0,0,0,1,0,1,2.0,1.0,2.0,3.0,1.0,21231,1.59e-01,2.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,3.0,2.0,NaN,NaN,1.0,NaN,2.0,2.0,21221,0.69,0.78,NaN,80.0,NaN,0.0,1.0,4.0,4.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,15.0,1.0,1.0,4.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,23.0,36.23,NN401,Knee Replacement,2016/17,NaN,NaN
38,0,2.0,0,2.0,2.0,1.0,2.0,0,1,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,21221,0.69,0.80,65.0,75.0,73.78,1.0,1.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,21.0,2.0,3.0,4.0,3.0,3.0,3.0,3.0,2.0,3.0,4.0,4.0,4.0,38.0,36.23,NN401,Knee Replacement,2016/17,NaN,NaN
39,0,2.0,0,2.0,2.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,1,0,1.0,1.0,1.0,2.0,2.0,11122,7.25e-01,2.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,99999,NaN,NaN,50.0,NaN,NaN,1.0,1.0,3.0,4.0,2.0,2.0,0.0,2.0,2.0,1.0,3.0,3.0,24.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,4.0,46.0,33.45,NN801,Knee Replacement,2016/17,NaN,NaN
40,0,2.0,0,1.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,1,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.59,70.0,85.0,65.52,0.0,2.0,4.0,2.0,3.0,2.0,1.0,0.0,2.0,3.0,2.0,2.0,23.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,3.0,4.0,4.0,46.0,31.85,NN801,Knee Replacement,2016/17,NaN,NaN
41,0,2.0,0,2.0,2.0,1.0,1.0,1,0,0,0,0,0,0,0,0,0,0,1,2.0,2.0,2.0,3.0,1.0,22231,5.50e-02,2.0,NaN,1.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,21211,0.81,0.63,75.0,80.0,71.98,0.0,1.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,8.0,3.0,3.0,4.0,3.0,4.0,3.0,4.0,2.0,3.0,4.0,4.0,4.0,41.0,28.81,NN801,Knee Replacement,2016/17,NaN,NaN
42,0,2.0,0,2.0,2.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,2.0,3.0,3.0,1.0,22331,-3.00e-03,2.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,22221,0.59,0.65,95.0,75.0,83.42,0.0,0.0,2.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0,1.0,0.0,2.0,2.0,2.0,1.0,0.0,0.0,2.0,2.0,2.0,2.0,16.0,28.96,NN801,Knee Replacement,2016/17,NaN,NaN
43,0,2.0,0,1.0,2.0,1.0,1.0,0,1,0,0,0,0,0,0,0,0,0,1,2.0,1.0,3.0,3.0,2.0,21332,3.00e-02,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.66,NaN,80.0,NaN,0.0,1.0,4.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,10.0,2.0,3.0,4.0,4.0,4.0,4.0,1.0,3.0,4.0,4.0,3.0,4.0,40.0,31.31,NN801,Knee Replacement,2016/17,NaN,NaN
44,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,2.0,1.0,2.0,3.0,1.0,21231,1.59e-01,2.0,NaN,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.68,75.0,97.0,75.75,0.0,1.0,4.0,2.0,3.0,1.0,0.0,0.0,2.0,3.0,1.0,2.0,19.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.0,4.0,4.0,4.0,3.0,42.0,34.36,NN801,Knee Replacement,2016/17,NaN,NaN
45,0,2.0,0,3.0,2.0,NaN,1.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,2.0,2.0,2.0,2.0,22222,5.16e-01,2.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,22222,0.52,0.75,54.0,60.0,67.83,1.0,3.0,3.0,1.0,4.0,1.0,3.0,0.0,1.0,3.0,2.0,2.0,24.0,1.0,2.0,3.0,2.0,4.0,1.0,2.0,0.0,2.0,3.0,1.0,1.0,22.0,36.91,NN801,Knee Replacement,2016/17,NaN,NaN
46,0,2.0,0,2.0,2.0,NaN,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,2.0,2.0,2.0,2.0,22222,5.16e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,11112,0.85,0.76,70.0,81.0,75.27,1.0,0.0,2.0,2.0,4.0,1.0,0.0,1.0,2.0,2.0,2.0,1.0,18.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,48.0,34.92,NN801,Knee Replacement,2016/17,NaN,NaN
47,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,1.0,1.0,2.0,2.0,1.0,11221,7.60e-01,2.0,NaN,1.0,1.0,2.0,1.0,2.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,21232,0.09,0.81,50.0,50.0,70.01,0.0,1.0,4.0,2.0,2.0,2.0,0.0,2.0,2.0,2.0,3.0,2.0,22.0,1.0,1.0,4.0,3.0,2.0,2.0,0.0,2.0,2.0,2.0,3.0,2.0,24.0,36.42,NN801,Knee Replacement,2016/17,NaN,NaN
48,0,2.0,0,2.0,2.0,1.0,1.0,0,1,0,0,0,0,0,0,0,1,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,11111,1.00,0.81,80.0,90.0,75.94,1.0,2.0,4.0,2.0,2.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,17.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,3.0,45.0,35.43,NN801,Knee Replacement,2016/17,NaN,NaN
49,0,2.0,0,2.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11311,0.56,0.88,100.0,85.0,92.09,1.0,2.0,2.0,2.0,3.0,2.0,1.0,0.0,3.0,4.0,4.0,3.0,27.0,2.0,3.0,3.0,2.0,4.0,3.0,2.0,1.0,2.0,4.0,2.0,2.0,30.0,40.53,NN801,Knee Replacement,2016/17,NaN,NaN
50,0,2.0,0,3.0,2.0,1.0,2.0,0,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11121,0.80,0.91,50.0,90.0,74.94,0.0,1.0,4.0,3.0,3.0,1.0,1.0,1.0,2.0,3.0,1.0,2.0,22.0,3.0,2.0,4.0,4.0,3.0,4.0,3.0,2.0,3.0,4.0,4.0,4.0,40.0,40.12,NN801,Knee Replacement,2016/17,NaN,NaN
51,0,2.0,0,2.0,2.0,1.0,1.0,0,1,0,1,1,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11211,0.88,0.69,50.0,70.0,58.07,1.0,0.0,3.0,2.0,2.0,1.0,1.0,0.0,1.0,2.0,2.0,2.0,17.0,3.0,3.0,4.0,3.0,4.0,3.0,4.0,0.0,4.0,4.0,3.0,3.0,38.0,30.64,NT202,Knee Replacement,2016/17,NaN,NaN
52,0,2.0,0,4.0,2.0,1.0,1.0,1,0,0,0,0,0,0,0,0,0,0,1,2.0,1.0,2.0,2.0,1.0,21221,6.91e-01,2.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,11111,1.00,0.73,80.0,88.0,72.22,0.0,1.0,4.0,4.0,2.0,2.0,0.0,0.0,2.0,3.0,3.0,2.0,23.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,47.0,34.47,NT202,Knee Replacement,2016/17,NaN,NaN